// =============================================================================
// Manuscript skeleton. Edit config.typ for the title/authors/abstract, then
// replace the placeholder sections below with real prose.
//
// DO NOT delete the "BODY START" / "BODY END" marker comments. Three separate
// tools slice the prose out of this file at those markers -- the word counter,
// the readability report, and the audiobook narrator -- and each fails loudly
// rather than guessing if they go missing.
// =============================================================================

#import "@preview/arkheion:0.1.0": arkheion, arkheion-appendices
// The Supporting Information carries its OWN reference list, independent of the
// main one: Typst refuses a second #bibliography ("multiple bibliographies are
// not yet supported"), so the SI's list is set by Alexandria instead. Every
// citation in si-body.typ is written with the "si-" prefix -- @si-key, not @key
// -- and this show rule is what routes those keys to the SI list. A bare @key
// in the SI still compiles and lands in the MAIN reference list instead, which
// is why `just prose-check` reports one.
#import "@preview/alexandria:0.2.0": alexandria
#import "config.typ": *
// Numbers generated by the analysis, read as #s("id"). See stats.typ. Delete
// this import along with stats.typ, stats.json and analysis/scripts/
// gen_stats.py if the project states no computed numbers in its prose.
#import "stats.typ": lit, n, s, todo
// Generated figures and tables, referenced as #fig("id") / #tbl("id"). See
// assets.typ. Delete this import along with assets.typ and assets.json if the
// project includes no generated figures or tables.
#import "assets.typ": fig, tbl
#import "code.typ": code-style

// The Word export (`just docx`) never compiles this preamble: it resolves the
// source to plain Typst and synthesizes its own front matter from config.typ,
// so the template below is the PDF's alone.
#let _template = arkheion.with(
  title: paper-title,
  authors: paper-authors,
  abstract: paper-abstract,
  keywords: paper-keywords,
  date: paper-date,
)

#show: _template
#show: code-style
// The prefix is a literal here and in si-body.typ's #bibliographyx call, on
// purpose: tools/prose_check.py and tools/resolve_typst.py both read it out of
// the source, and a #let in config.typ would be invisible to a text read.
// `just prose-check` reports the two drifting apart.
#show: alexandria(prefix: "si-", read: p => read(p))

// Print just a cross-reference's number (e.g. "3") with no "Figure"/"Table"/
// "Section" prefix, for enumerations like "Figures 2 and 3".
#let refn(l) = ref(l, supplement: none)

// Graphical abstract -- the journal's "TOC graphic". Declared once, here, and
// PLACED by `toc-placement`: "preprint" puts it under the abstract, where an
// archive server shows it; "journal" puts it on the last page of the main
// manuscript under the label ACS prescribes; "none" leaves it out. The build
// passes the placement from journal.toml as `--input toc=...`, so the PDF and
// the Word export differ without this file changing; the Word resolver reads
// the same two bindings. `just check-journal` measures the file against the
// journal's box. Set toc-graphic to `none` if the paper has no graphic.
#let toc-graphic = fig("fig.toc", width: 3.25in)
#let toc-caption = [
  The pipeline in one picture. Replace the graphic with the paper's own; see
  analysis/scripts/gen_toc_figure.py.
]
#let toc-placement = sys.inputs.at("toc", default: "preprint")
#if toc-placement not in ("preprint", "journal", "none") {
  panic("--input toc must be preprint, journal or none, got " + toc-placement)
}
#let toc-block = if toc-graphic == none [] else [
  #align(center)[
    #toc-graphic
    #v(4pt)
    #text(9pt, style: "italic", toc-caption)
  ]
]
#if toc-placement == "preprint" { toc-block }

// >>> BODY START -- everything from here to BODY END is counted as prose and narrated.

= Introduction

Replace this with the introduction. The sections below are a starting structure,
not an example to preserve.

Citation, cross-reference, figure, table, and equation are each shown once, so
the skeleton compiles and the numbering resolves before anything is written
@lovelace1843. A second one @hopper1952 keeps the reference list plural, and
keeps every entry in `references.bib` cited: `just prose-check` reports one that
is not. Delete what you do not need. Coverage of the constructs the tooling
handles specially does not live here, it lives in `tests/fixture.typ`, which
`just test` checks and which is never part of the manuscript.

A number the analysis computes is read rather than typed: across #s(
  "cohort.n_conditions",
) conditions and #s("cohort.total_n") participants, the treated group scored #s(
  "effect.treated_over_control",
) over control, a #s("effect.treated_fold")-fold change, best in #s(
  "effect.best_condition",
). Each of those comes from `analysis/scripts/gen_stats.py` and fails the build
if it stops existing. The last one is a label rather than a number, which is why
it carries no guard.

= Methods <sec:methods>

Replace this with the methods. An equation, for reference:

$ E = sum_(i=1)^n w_i (x_i - mu)^2 $

= Results

Replace this with the results. See @fig:example and @tbl:example. Tables an
analysis writes are in @sec:si-tables, and how to reproduce every number is in
@sec:si-repro.

#figure(
  fig("fig.example", width: 70%),
  caption: [
    Placeholder. Written by `analysis/scripts/gen_example_figure.py`; `just
    check` reports it stale if the analysis changes and it is not regenerated.
  ],
) <fig:example>

#figure(
  table(
    columns: 3,
    align: (left, right, right),
    table.header([Condition], [Observed], [Expected]),
    [Control], [1.02], [1.00],
    [Treated], [2.11], [2.00],
  ),
  caption: [Placeholder, hand-written. A table whose numbers come from an
    analysis belongs in `si/` instead, written by a script.],
) <tbl:example>

= Conclusions

Replace this with the conclusions. Keep the preamble, the marker comments, the
back matter below, and the Supporting Information transition at the foot of this
file.

// <<< BODY END

#heading(numbering: none)[Associated Content]

*Supporting Information*

The Supporting Information is appended to this document and is available free of
charge.

*Data and Code Availability*

Name each dataset's repository and accession here, and the DOI of the archived
code (a Zenodo, figshare or Software Heritage record, not only a Git URL).
`just check-submission` fails on an accession the text cites but this statement
omits.

*Author Contributions*

Describe each author's contribution here. Replace this sentence.

*Notes*

The authors declare no competing financial interest.

#heading(numbering: none)[Acknowledgment]

Funding sources and acknowledgments go here. If any part of the work used
generative AI tooling, disclose it in this paragraph.

#bibliography("references.bib", title: [References], style: paper-bib-style)

// The graphical abstract in the journal's layout: the last page of the main
// manuscript, before the SI, under the label the ACS guideline prescribes.
#if toc-placement == "journal" {
  pagebreak()
  heading(level: 1, numbering: none, outlined: false)[For Table of Contents
    Only]
  toc-block
}

// ===================== Supporting Information (appendix) =====================
// The SI is appended here as an appendix so the whole manuscript is a single
// compilation with one label namespace -- every @fig/@tbl/@sec resolves across
// the main text and the SI, and numbers can never drift out of sync.
// From this point on, figures and tables restart at S1, S2, ... and SI headings
// number S1, S2, ...  (page and line numbering stay continuous.)
#pagebreak()

// The first page of the SI, for `just main-pdf` and `just si-pdf`
// (tools/submission.py), which read it back with `typst query` and compile
// the two halves as page ranges. Never hardcode the number: it moves whenever
// the main text changes length. Emits no layout. Keep it directly after the
// pagebreak above, and keep the journal-layout graphical abstract before it,
// so the main text ends with that page and the SI starts cleanly after it.
#context [#metadata(here().page()) <si-start>]

#counter(figure.where(kind: image)).update(0)
#counter(figure.where(kind: table)).update(0)
#counter(heading).update(0)
#show figure.where(kind: image): set figure(numbering: n => "S" + str(n))
#show figure.where(kind: table): set figure(numbering: n => "S" + str(n))
#set heading(numbering: (..n) => "S" + n.pos().map(str).join("."))

// The SI's title block, for the PDF. The Word export does not read this
// layout: tools/resolve_typst.py synthesizes the same block as a real heading
// from the front matter, so it lands in Word's navigation pane.
#align(center)[
  #text(15pt, weight: "bold")[Supporting Information]
  #v(2pt)
  #text(13pt)[#paper-title]
  #v(2pt)
  #text(10pt, style: "italic")[#si-authors]
]

#v(1em)

#include "si-body.typ"
