// =============================================================================
// Manuscript skeleton. Edit config.typ for the title/authors/abstract, then
// replace the placeholder sections below with real prose.
//
// DO NOT delete the "BODY START" / "BODY END" marker comments. Three separate
// tools slice the prose out of this file at those markers -- the word counter,
// the readability report, and the audiobook narrator -- and each fails loudly
// rather than guessing if they go missing.
//
// The docx-mode machinery in this preamble is load-bearing for `just docx` and
// is inert on the PDF path. Read the comments before changing it.
// =============================================================================

#import "@preview/arkheion:0.1.0": arkheion, arkheion-appendices
#import "config.typ": *
// Numbers generated by the analysis, read as #s("id"). See stats.typ. Delete
// this import along with stats.typ, stats.json and analysis/scripts/
// gen_stats.py if the project states no computed numbers in its prose.
#import "stats.typ": n, s
// Generated figures and tables, referenced as #fig("id") / #tbl("id"). See
// assets.typ. Delete this import along with assets.typ and assets.json if the
// project includes no generated figures or tables.
#import "assets.typ": fig, tbl

// Word-export path (`just docx`): compiling with --input docx=true bypasses the
// arkheion template. Its front matter and heading styling are built from layout-only
// primitives (page/pad/line/block) that Typst's HTML export discards, which silently
// drops every section heading and the abstract. In docx mode we skip the template and
// emit plain front matter instead, so headings survive as real <h2>/<h3> elements.
// With the flag absent this is inert and the PDF is byte-for-byte unchanged.
#let docx-mode = sys.inputs.at("docx", default: "") == "true"

#let _template = arkheion.with(
  title: paper-title,
  authors: paper-authors,
  abstract: paper-abstract,
  keywords: paper-keywords,
  date: paper-date,
)

// Apply the template for PDF; in docx mode pass the document through untouched.
#show: if docx-mode { doc => doc } else { _template }

// arkheion normally supplies heading numbering; without it the `@sec:` cross-references
// fail to resolve, so restore it on the docx path only. The SI's own "S1"-style
// numbering is set later in the file and still overrides this for the appendix.
#set heading(numbering: "1.") if docx-mode

// Typst's HTML export drops equations outright, which would gut any sentence built
// around inline math. html.frame keeps each one as an SVG that typst2docx.py then
// rasterizes back inline. Identity on the PDF path, so print output is unchanged.
#show math.equation: it => if docx-mode { html.frame(it) } else { it }

// Front matter for the Word/HTML path only (the template would normally supply it).
// The author line comes from config.typ, built from the same author list the PDF
// template uses, so the superscript affiliation markers cannot drift.
#if docx-mode {
  text(17pt, weight: "bold", paper-title)
  parbreak()
  text(11pt, paper-author-line)
  parbreak()
  for (i, affil) in paper-affiliations.enumerate() {
    text(9pt, style: "italic", super(str(i + 1)) + " " + affil)
    linebreak()
  }
  parbreak()
  text(10pt, strong("Abstract.") + " " + paper-abstract)
  parbreak()
  text(9pt, strong("Keywords: ") + paper-keywords.join(", "))
}

// Print just a cross-reference's number (e.g. "3") with no "Figure"/"Table"/
// "Section" prefix, for enumerations like "Figures 2 and 3".
#let refn(l) = ref(l, supplement: none)

// >>> BODY START -- everything from here to BODY END is counted as prose and narrated.

= Introduction

Replace this with the introduction. The sections below are a starting structure,
not an example to preserve.

Citation, cross-reference, figure, table, and equation are each shown once, so
the skeleton compiles and the numbering resolves before anything is written
@lovelace1843. A second one @hopper1952 keeps the reference list plural, and
keeps every entry in `references.bib` cited: `just prose-check` reports one that
is not. Delete what you do not need. Coverage of the constructs the tooling
handles specially does not live here, it lives in `tests/fixture.typ`, which
`just test` checks and which is never part of the manuscript.

A number the analysis computes is read rather than typed: across #s(
  "cohort.n_conditions",
) conditions and #s("cohort.total_n") participants, the treated group scored #s(
  "effect.treated_over_control",
) over control, a #s("effect.treated_fold")-fold change, best in #s(
  "effect.best_condition",
). Each of those comes from `analysis/scripts/gen_stats.py` and fails the build
if it stops existing. The last one is a label rather than a number, which is why
it carries no guard.

= Methods <sec:methods>

Replace this with the methods. An equation, for reference:

$ E = sum_(i=1)^n w_i (x_i - mu)^2 $

= Results

Replace this with the results. See @fig:example and @tbl:example.

#figure(
  fig("fig.example", width: 70%),
  caption: [
    Placeholder. Written by `analysis/scripts/gen_example_figure.py`; `just
    check` reports it stale if the analysis changes and it is not regenerated.
  ],
) <fig:example>

#figure(
  table(
    columns: 3,
    align: (left, right, right),
    table.header([Condition], [Observed], [Expected]),
    [Control], [1.02], [1.00],
    [Treated], [2.11], [2.00],
  ),
  caption: [Placeholder, hand-written. A table whose numbers come from an
    analysis belongs in `si/` instead, written by a script.],
) <tbl:example>

= Conclusions

Replace this with the conclusions. Keep the preamble, the marker comments, the
back matter below, and the Supporting Information transition at the foot of this
file.

// <<< BODY END

#heading(numbering: none)[Associated Content]

*Supporting Information*

The Supporting Information is appended to this document and is available free of
charge.

*Author Contributions*

Describe each author's contribution here. Replace this sentence.

*Notes*

The authors declare no competing financial interest.

#heading(numbering: none)[Acknowledgment]

Funding sources and acknowledgments go here. If any part of the work used
generative AI tooling, disclose it in this paragraph.

#bibliography("references.bib", title: [References], style: paper-bib-style)

// ===================== Supporting Information (appendix) =====================
// The SI is appended here as an appendix so the whole manuscript is a single
// compilation with one label namespace -- every @fig/@tbl/@sec resolves across
// the main text and the SI, and numbers can never drift out of sync.
// From this point on, figures and tables restart at S1, S2, ... and SI headings
// number S1, S2, ...  (page and line numbering stay continuous.)
#pagebreak()

#counter(figure.where(kind: image)).update(0)
#counter(figure.where(kind: table)).update(0)
#counter(heading).update(0)
#show figure.where(kind: image): set figure(numbering: n => "S" + str(n))
#show figure.where(kind: table): set figure(numbering: n => "S" + str(n))
#set heading(numbering: (..n) => "S" + n.pos().map(str).join("."))

// Same trap as any centred block: HTML export discards the align/block wrapper AND
// its contents, so on the Word path this whole title block vanishes and the main
// text runs straight into Section S1 with nothing marking the boundary. Emit it as
// plain content there -- a real heading, so it also lands in Word's navigation pane
// -- and keep the centred layout for the PDF.
#if docx-mode [
  #heading(level: 1, numbering: none, outlined: false)[Supporting Information]

  #text(13pt)[#paper-title]

  #text(10pt, style: "italic")[#si-authors]
] else [
  #align(center)[
    #text(15pt, weight: "bold")[Supporting Information]
    #v(2pt)
    #text(13pt)[#paper-title]
    #v(2pt)
    #text(10pt, style: "italic")[#si-authors]
  ]

  #v(1em)
]

#include "si-body.typ"
