// Supporting Information body -- included by paper.typ as an appendix (single
// combined document, one label namespace, so @fig/@tbl/@sec resolve across the
// main text and the SI). The SI title, page/margin setup, and S-prefixed
// numbering (Figure/Table/Section "S" prefixes) are all applied by paper.typ at
// the include site. This file is body-only and is NOT compiled on its own.
//
// Tables under si/ are auto-generated by the scripts in scripts/; never edit
// them by hand. See scripts/gen_example_table.py for the contract.

// Print just a cross-reference's number (e.g. "S2") with no "Table"/"Figure"
// prefix, for enumerations like "Tables S1 and S2".
#let refn(l) = ref(l, supplement: none)

// Numbers generated by the analysis, read as #s("id"). Imported HERE as well as
// in paper.typ because `include` gives this file its own scope: it does not
// inherit the importing file's bindings, so without this line an #s("id") in the
// SI fails with `unknown variable: s` even though paper.typ imports it.
//
// The SI is where generated numbers belong most, being the data-heavy half, and
// the extractors resolve them here already -- the word count, the readability
// report and the SI narration all read #s() out of this file.
//
// Delete this import along with stats.typ, si/stats.json and analysis/scripts/
// gen_stats.py if the project states no computed numbers in its prose.
#import "stats.typ": n, s

Replace this with a summary of what the Supporting Information contains. Text
above the first `=` heading is the SI audiobook's opening chapter, so keep any
orienting material here.

= Auto-generated tables <sec:si-tables>

Replace this section. The table below is written by
`analysis/scripts/gen_example_table.py` and included rather than pasted, so
re-running the analysis updates the manuscript. Regenerate with `just assets`.

#figure(
  include "si/example_table.typ",
  caption: [Placeholder, auto-generated. Do not edit `si/example_table.typ`
    directly, as the next `just assets` overwrites it.],
) <tbl:si-example>

Cross-references resolve in both directions, so @tbl:si-example and Table #refn(
  <tbl:si-example>,
) work here, as does @sec:methods in the main text.

= Reproducibility <sec:si-repro>

Replace this with where the data, code, and analysis scripts live, and which
versions were used. Accession numbers, a repository URL, and the command lines
needed to reproduce every number belong here. Keep the section, since most
journals now require it.
