// Supporting Information body -- included by paper.typ as an appendix (single
// combined document, one label namespace, so @fig/@tbl/@sec resolve across the
// main text and the SI). The SI title, page/margin setup, and S-prefixed
// numbering (Figure/Table/Section "S" prefixes) are all applied by paper.typ at
// the include site. This file is body-only and is NOT compiled on its own.
//
// Tables under si/ are auto-generated by the scripts in scripts/; never edit
// them by hand. See scripts/gen_example_table.py for the contract.

// Print just a cross-reference's number (e.g. "S2") with no "Table"/"Figure"
// prefix, for enumerations like "Tables S1 and S2".
#let refn(l) = ref(l, supplement: none)

// Numbers generated by the analysis, read as #s("id"). Imported HERE as well as
// in paper.typ because `include` gives this file its own scope: it does not
// inherit the importing file's bindings, so without this line an #s("id") in the
// SI fails with `unknown variable: s` even though paper.typ imports it.
//
// The SI is where generated numbers belong most, being the data-heavy half, and
// the extractors resolve them here already -- the word count, the readability
// report and the SI narration all read #s() out of this file.
//
// Delete this import along with stats.typ, stats.json and analysis/scripts/
// gen_stats.py if the project states no computed numbers in its prose.
#import "stats.typ": lit, n, s, todo
#import "assets.typ": fig, tbl

// The SI's own reference list. Cite in this file as @si-key, never @key: the
// "si-" prefix is what routes a citation to the list at the foot of this file
// rather than to the main text's. A bare @key here compiles and silently joins
// the MAIN reference list, so `just prose-check` reports one. The matching
// `#show: alexandria(prefix: "si-", ...)` lives in paper.typ.
//
// `bibliographyx` is Alexandria's own, less one thing: an SI that cites
// nothing prints nothing, where Alexandria would still print a bare
// "References" heading. It keeps Alexandria's name and arguments on purpose:
// the tools read the `#bibliographyx(...)` call at the foot of this file
// literally, and the Word export drops the list by the same rule.
#import "@preview/alexandria:0.2.0": (
  get-bibliography, load-bibliography, render-bibliography,
)
#let bibliographyx(
  path,
  prefix: auto,
  title: auto,
  full: false,
  style: "ieee",
) = {
  load-bibliography(path, prefix: prefix, full: full, style: style)
  context {
    let bib = get-bibliography(prefix)
    if bib.references.len() > 0 { render-bibliography(bib, title: title) }
  }
}
#import "config.typ": paper-bib-style

Replace this with a summary of what the Supporting Information contains. Text
above the first `=` heading is the SI audiobook's opening chapter, so keep any
orienting material here.

= Auto-generated tables <sec:si-tables>

Replace this section. The table below is written by
`analysis/scripts/gen_example_table.py` and included rather than pasted, so
re-running the analysis updates the manuscript. Regenerate with `just assets`.

#figure(
  tbl("tbl.example"),
  caption: [Placeholder, auto-generated. Do not edit `si/example_table.typ`
    directly, as the next `just assets` overwrites it.],
) <tbl:si-example>

Cross-references resolve in both directions, so @tbl:si-example and Table #refn(
  <tbl:si-example>,
) work here, as does @sec:methods in the main text.

= Reproducibility <sec:si-repro>

Replace this with where the data, code, and analysis scripts live, and which
versions were used. Accession numbers, a repository URL, and the command lines
needed to reproduce every number belong here. Keep the section, since most
journals now require it. A work cited only in the SI is cited with the prefix
@si-hopper1952 and appears in the SI's reference list below, numbered from 1,
not in the main text's.

// The SI's reference list. `full: false` is Alexandria's default, so only the
// works actually cited above are printed. Keep this call LAST in the file and
// at the top level: the `#set` applies to everything after it, which is why
// the SI's own S1/S2 section numbering is not disturbed, and tools/
// resolve_typst.py rewrites the call itself into a plain #bibliography for the
// Word export. The <si-references> label is what wordcount.typ excludes, so
// the list is no more counted as SI prose than the main one is as main text.
#set heading(numbering: none)
#bibliographyx(
  "references.bib",
  prefix: "si-",
  title: [References],
  style: paper-bib-style,
) <si-references>
