"""`paper sync`: write the files a paper must hold on disk, and check them.

Most of the toolchain is read from the installed package (tools/paths.py).
A few files cannot be: `just` reads a justfile, Typst resolves imports inside
the compile root, the analysis runs in its own environment, and decks import
slides/theme.typ. `paper sync` writes those from the package, each with a
header saying so, and records their hashes in .paper/scaffold.lock.json.
`paper sync --check` (the first `just verify` stage) fails on a missing,
edited or out-of-date file, a lock from another release, or a toolchain
directory a finished migration would have removed. docs/package.md has the
design.
"""
from __future__ import annotations

import hashlib
import json
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

from . import data_dir, use_tools, version

LOCK = ".paper/scaffold.lock.json"
DOCS_MIRROR = ".paper/docs"
SCHEMA = 1

# Always written.
ALWAYS = ("justfile", "stats.typ", "assets.typ", "code.typ", "wordcount.typ",
          "wordcount-sections.typ")
# Written when analysis/scripts/ exists: the helpers every generator imports,
# and the four toolchain modules they share with the checks, because the
# analysis environment does not install this package.
ANALYSIS_HELPERS = ("analysis/scripts/_stats.py", "analysis/scripts/_assets.py",
                    "analysis/scripts/_provenance.py")
ANALYSIS_TOOLCHAIN = ("atomic_io.py", "manifest_validation.py", "hashcache.py",
                      "paths.py")
TOOLCHAIN_DIR = "analysis/scripts/_toolchain"
# Written when audio/config.py exists (the paper's own narration settings).
AUDIO = ("audio/extract_prose.py", "audio/make_audiobook.py", "audio/make_cover.py")
# Written when slides/ exists, unless project.toml declares the paper's own
# theme ([slides] theme, 4.1.0): the same escape hatch as 3.27.0's
# [word] reference. The declared file is then the paper's, listed under the
# lock's overrides, and slides/theme.typ is not written.
SLIDES = ("slides/theme.typ",)

# A paper file at one of these wins over the package's copy (tools/paths.py
# locate()) and is the paper's own: never written, never flagged, listed in
# the lock under "overrides".
OVERRIDE_GLOBS = ("word/*.docx", "journals/*.toml")

# Toolchain directories that live only in the package. One left in a paper is
# a half-finished migration: its files would never be read.
PACKAGE_ONLY_DIRS = ("tools", "tests", "docs")


class SyncError(Exception):
    pass


def sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def is_scaffold_checkout(root: Path) -> bool:
    return root.resolve() == data_dir().resolve()


def header_lines(release: str) -> list[str]:
    return [
        f"GENERATED by `paper sync` from paper-scaffold {release}. Do not edit:",
        "`paper sync --check` (in `just verify`) fails on an edit, and the next",
        "sync would refuse to overwrite it. Paper recipes go in project.just;",
        "gates, Word steps and sources in project.toml (.paper/docs/hooks.md).",
    ]


def with_header(target: str, text: str, release: str) -> str:
    mark = "//" if target.endswith(".typ") else "#"
    block = "".join(f"{mark} {line}\n" for line in header_lines(release))
    if text.startswith("#!"):
        first, _, rest = text.partition("\n")
        return f"{first}\n{block}{rest}"
    return block + "\n" + text if not text.startswith(mark) else block + text


def owned_theme(root: Path) -> str | None:
    """project.toml's [slides] theme: the paper's own deck theme, or None."""
    if not (root / "project.toml").is_file():
        return None
    use_tools()
    import project_hooks
    try:
        theme = project_hooks.load(root).slides_theme
    except ValueError as e:
        raise SyncError(str(e)) from None
    if theme and not (root / theme).is_file():
        raise SyncError(f"project.toml [slides] theme names a missing file: {theme}")
    return theme


def generated(root: Path) -> dict[str, tuple[Path, str]]:
    """{target: (source in the package, content to write)} for this paper."""
    data, release = data_dir(), version()
    plan: dict[str, Path] = {name: data / name for name in ALWAYS}
    if (root / "analysis" / "scripts").is_dir():
        plan.update({name: data / name for name in ANALYSIS_HELPERS})
        plan.update({f"{TOOLCHAIN_DIR}/{name}": data / "tools" / name
                     for name in ANALYSIS_TOOLCHAIN})
    if (root / "audio" / "config.py").is_file():
        plan.update({name: data / name for name in AUDIO})
    if (root / "slides").is_dir() and owned_theme(root) is None:
        plan.update({name: data / name for name in SLIDES})
    out = {}
    for target, source in sorted(plan.items()):
        if not source.is_file():
            raise SyncError(f"the installed package has no {source.relative_to(data)}")
        out[target] = (source, with_header(target, source.read_text(encoding="utf-8"), release))
    return out


def overrides(root: Path) -> dict[str, str]:
    found = {}
    for pattern in OVERRIDE_GLOBS:
        for path in sorted(root.glob(pattern)):
            if path.is_file():
                found[path.relative_to(root).as_posix()] = sha(path.read_bytes())
    theme = owned_theme(root)
    if theme:
        found[theme] = sha((root / theme).read_bytes())
    return dict(sorted(found.items()))


def read_lock(root: Path) -> dict | None:
    path = root / LOCK
    if not path.is_file():
        return None
    try:
        lock = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        raise SyncError(f"{LOCK} is not valid JSON: {e}") from None
    if lock.get("schema_version") != SCHEMA:
        raise SyncError(f"{LOCK}: unknown schema_version {lock.get('schema_version')!r}")
    return lock


def read_pin(root: Path) -> str | None:
    """The `paper-scaffold ...` requirement in the paper's pyproject.toml."""
    py = root / "pyproject.toml"
    if not py.is_file():
        return None
    try:
        import tomllib
    except ModuleNotFoundError:  # Python 3.10
        import tomli as tomllib  # type: ignore[no-redef]
    deps = tomllib.loads(py.read_text()).get("project", {}).get("dependencies", [])
    for dep in deps:
        if re.match(r"paper-scaffold\b", dep.strip()):
            return dep.strip()
    return None


def upgrade_notes(frm: str, to: str | None = None) -> list[str]:
    """The HISTORY.md "Upgrade:" lines between two releases, still to do."""
    use_tools()
    import upgrade_plan
    try:
        items = upgrade_plan.installed_notes(frm, to)
    except upgrade_plan.PlanError:
        return []
    return [f"[{u.version}] {u.text}" for u in items if u.status == "do"]


def mirror_docs(root: Path) -> None:
    src, dest = data_dir() / "docs", root / DOCS_MIRROR
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest, ignore=shutil.ignore_patterns("__pycache__"))
    history = data_dir() / "HISTORY.md"
    if history.is_file():
        shutil.copyfile(history, dest / "HISTORY.md")


@dataclass
class Result:
    written: list[str]
    unchanged: list[str]
    removed: list[str]
    overrides: dict[str, str]


def sync(root: Path, force: bool = False, replace: tuple[str, ...] = ()) -> Result:
    """Write the generated files and the lock.

    Refuses (SyncError, nothing written) when a file it would overwrite is
    neither what the lock recorded nor what it would write: that is an edit.
    `force` overwrites anyway; `replace` names paths the caller has already
    established are safe to overwrite (paper migrate: pristine copies).
    """
    root = root.resolve()
    if is_scaffold_checkout(root):
        raise SyncError("this is the scaffold checkout: its toolchain is the "
                        "repository itself, nothing to sync")
    lock = read_lock(root) or {}
    locked = lock.get("files", {})
    plan = generated(root)
    refused = []
    for target, (_, content) in plan.items():
        path = root / target
        if not path.is_file() or force or target in replace:
            continue
        current = path.read_bytes()
        if current == content.encode() or locked.get(target) == sha(current):
            continue
        refused.append(target + ("  (edited since the last sync)" if target in locked
                                 else "  (not written by paper sync)"))
    if refused:
        raise SyncError(
            "refusing to overwrite:\n  " + "\n  ".join(refused)
            + "\nMove the change into project.just, project.toml or hooks/ "
            "(.paper/docs/hooks.md), or rerun with --force to discard it.")
    written, unchanged, removed = [], [], []
    for target, (_, content) in plan.items():
        path = root / target
        data = content.encode()
        if path.is_file() and path.read_bytes() == data:
            unchanged.append(target)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        written.append(target)
    # A file an earlier release generated and this one does not: remove it
    # when it is still exactly what was generated.
    owned = owned_theme(root)
    for target, digest in locked.items():
        path = root / target
        if target == owned:
            continue  # declared the paper's own ([slides] theme): never removed
        if target not in plan and path.is_file() and sha(path.read_bytes()) == digest:
            path.unlink()
            removed.append(target)
    found = overrides(root)
    new_lock = {
        "schema_version": SCHEMA,
        "scaffold": {"version": version(), "pin": read_pin(root)},
        "files": {t: sha(c.encode()) for t, (_, c) in plan.items()},
        "overrides": found,
    }
    (root / LOCK).parent.mkdir(parents=True, exist_ok=True)
    (root / LOCK).write_text(json.dumps(new_lock, indent=2) + "\n")
    mirror_docs(root)
    return Result(written, unchanged, removed, found)


def check(root: Path) -> list[str]:
    """Every reason the paper's generated files are not what this release writes."""
    root = root.resolve()
    if is_scaffold_checkout(root):
        return []
    problems = []
    try:
        lock = read_lock(root)
    except SyncError as e:
        return [str(e)]
    if lock is None:
        return [f"no {LOCK}: run `uv run paper sync`"]
    installed = version()
    if lock.get("scaffold", {}).get("version") != installed:
        problems.append(f"{LOCK} was written by paper-scaffold "
                        f"{lock.get('scaffold', {}).get('version')}, the installed "
                        f"package is {installed}: run `uv run paper sync`")
    locked = lock.get("files", {})
    plan = generated(root)
    for target, (_, content) in plan.items():
        path = root / target
        if not path.is_file():
            problems.append(f"{target}: missing (run `uv run paper sync`)")
            continue
        current = sha(path.read_bytes())
        if target in locked and current != locked[target]:
            problems.append(f"{target}: edited since `paper sync` wrote it; move "
                            "the change into project.just / project.toml / hooks/")
        elif current != sha(content.encode()):
            problems.append(f"{target}: not what paper-scaffold {installed} writes "
                            "(run `uv run paper sync`)")
    for target in sorted(set(locked) - set(plan) - {owned_theme(root)}):
        if (root / target).exists():
            problems.append(f"{target}: generated by an earlier release, no longer "
                            "written (run `uv run paper sync`)")
    for name in PACKAGE_ONLY_DIRS:
        if (root / name).is_dir():
            problems.append(f"{name}/: the toolchain's {name}/ now comes from the "
                            "package; this copy is never read (finish the "
                            "migration: .paper/docs/package.md"
                            + ("; the paper's own notes go in notes/"
                               if name == "docs" else "") + ")")
    return problems


def describe(root: Path, lock: dict | None) -> str:
    lock = lock or {}
    pin = lock.get("scaffold", {}).get("pin") or "unpinned"
    n = len(lock.get("files", {}))
    line = f"paper-scaffold {version()} ({pin}); {n} generated file(s) current"
    over = lock.get("overrides") or {}
    if over:
        line += "; local overrides: " + ", ".join(sorted(over))
    return line


def main_sync(root: Path, check_only: bool, force: bool) -> int:
    if is_scaffold_checkout(root):
        print("scaffold checkout: the toolchain is this repository, nothing to sync")
        return 0
    if check_only:
        try:
            problems = check(root)
        except SyncError as e:
            # A project.toml typo or a missing [slides] theme: one line, not a
            # traceback, and a failing exit like any other problem.
            print(f"paper sync --check: {e}", file=sys.stderr)
            return 1
        if problems:
            for p in problems:
                print(f"paper sync --check: {p}", file=sys.stderr)
            return 1
        print(describe(root, read_lock(root)))
        return 0
    try:
        before = read_lock(root)
        old = (before or {}).get("scaffold", {}).get("version")
        if old and old != version():
            notes = upgrade_notes(old, version())
            print(f"paper-scaffold {old} -> {version()}: "
                  f"{len(notes)} Upgrade: line(s) to read")
            for i, n in enumerate(notes, 1):
                print(f"  {i:>2}. {n}")
        result = sync(root, force=force)
    except SyncError as e:
        print(f"paper sync: {e}", file=sys.stderr)
        return 1
    print(f"paper sync: wrote {len(result.written)}, unchanged {len(result.unchanged)}"
          + (f", removed {len(result.removed)}" if result.removed else ""))
    for t in result.written:
        print(f"  wrote   {t}")
    for t in result.removed:
        print(f"  removed {t}")
    for t in result.overrides:
        print(f"  override (the paper's own) {t}")
    return 0
