"""Declare the numbers the manuscript states in prose, with guards.

WHY THIS EXISTS. Tables and figures have always tracked the analysis, because a
script writes them. Numbers written into sentences are typed by hand, and they
drift: a unit error, a stale percentage after a re-run, a value corrected in the
table but not in the paragraph beside it. A staleness checker can only notice
drift after the fact. Sourcing the sentence from the same data as the table makes
the two unable to disagree.

WHAT A GUARD IS FOR. A generated number can still make a sentence read wrong.
"counts fell by #s(...)%" is correct only while the value is negative; the day a
re-run turns it positive, the paper says "fell by -3.1%" and nothing complains.
`sign` and `between` are assertions about what the analysis is allowed to
produce. They fail HERE, when the number changes, naming the sentence's
assumption -- not in review.

USAGE. One script per project writes the whole file:

    from _stats import Stats

    st = Stats()
    st.add("recovery.mean", 84.23, fmt=".1f", unit="%",
           desc="Mean recovery across replicates",
           sign="+", between=(0, 100),
           source="scripts/example_data.csv")
    st.write()

The manuscript then reads it as `#s("recovery.mean")`, which resolves at compile
time and fails the build on an unknown key.

IDS. Dotted, flat, and stable: `<group>.<name>`. The dots are part of the key,
not nesting -- one flat table is greppable, listable and diffable, and an ID can
be moved between groups without restructuring the file.
"""
from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAPER = HERE.parent.parent            # analysis/scripts/ -> analysis/ -> paper/
OUT = PAPER / "si" / "stats.json"

ABOUT = ("AUTO-GENERATED by analysis/scripts/gen_stats.py -- do not edit by hand. "
         "Read from the manuscript as #s(\"<id>\").")


class StatError(Exception):
    """A declared value violated the guard the prose depends on."""


class Stats:
    """Collects declared values, checks their guards, writes si/stats.json."""

    def __init__(self) -> None:
        self._values: dict[str, dict] = {}

    def add(self, id: str, value, *, fmt: str = "", unit: str = "",
            desc: str = "", sign: str | None = None,
            between: tuple[float, float] | None = None,
            source: str = "") -> None:
        """Declare one number.

        `value`   the raw value. A str is allowed for things that are not
                  numbers (a name, a flag); guards are then rejected rather than
                  silently skipped.
        `fmt`     Python format spec for the DISPLAY string: ".1f", ",.0f", "+.2f".
                  Rounding lives here, next to the analysis, rather than being
                  reimplemented in Typst.
        `sign`    "+", "-", or "nonzero". What the prose assumes about direction.
        `between` (lo, hi) inclusive. A plausibility band: catches a unit error
                  or a percentage that lands at 8400.
        `desc`    what the number is, for someone auditing the file later.
        `source`  where it came from, relative to analysis/.
        """
        if id in self._values:
            raise StatError(f"{id!r} declared twice")
        if not id or " " in id:
            raise StatError(f"{id!r} is not a usable id (no spaces, not empty)")

        numeric = isinstance(value, (int, float)) and not isinstance(value, bool)
        if not numeric and (sign is not None or between is not None):
            raise StatError(
                f"{id!r} has a guard but its value {value!r} is not numeric. "
                f"Drop the guard, or pass the number rather than a pre-formatted "
                f"string.")

        if numeric:
            self._check(id, float(value), sign, between)

        expect: dict = {}
        if sign is not None:
            expect["sign"] = sign
        if between is not None:
            expect["min"], expect["max"] = between

        self._values[id] = {
            "value": value,
            "display": format(value, fmt) if fmt else str(value),
            "unit": unit,
            "desc": desc,
            "expect": expect,
            "source": source,
        }

    @staticmethod
    def _check(id: str, v: float, sign: str | None,
               between: tuple[float, float] | None) -> None:
        if sign is not None:
            ok = {"+": v > 0, "-": v < 0, "nonzero": v != 0}
            if sign not in ok:
                raise StatError(
                    f"{id!r}: sign must be '+', '-' or 'nonzero', got {sign!r}")
            if not ok[sign]:
                raise StatError(
                    f"{id!r} is {v}, which violates sign '{sign}'.\n"
                    f"  The prose is written assuming this number is "
                    f"{ {'+': 'positive', '-': 'negative', 'nonzero': 'nonzero'}[sign] }. "
                    f"Either the analysis changed meaning, or the sentence that "
                    f"reads it needs rewording.")
        if between is not None:
            lo, hi = between
            if not lo <= v <= hi:
                raise StatError(
                    f"{id!r} is {v}, outside the expected range [{lo}, {hi}].\n"
                    f"  Usually a unit error or a changed denominator. Widen the "
                    f"band if the new value is genuinely right.")

    def write(self, out: Path | None = None) -> int:
        """Write si/stats.json and report what is unguarded."""
        p = out or OUT
        p.parent.mkdir(exist_ok=True)
        p.write_text(json.dumps(
            {"_about": ABOUT, "values": dict(sorted(self._values.items()))},
            indent=2, sort_keys=False) + "\n")

        # An unguarded number is not an error -- plenty of values have no
        # meaningful sign or range. It is reported so the set stays visible
        # rather than quietly becoming the default.
        bare = [k for k, v in self._values.items()
                if not v["expect"] and isinstance(v["value"], (int, float))]
        print(f"wrote {p.relative_to(PAPER)}  ({len(self._values)} values)")
        if bare:
            print(f"  {len(bare)} numeric value(s) with no sign/range guard: "
                  f"{', '.join(sorted(bare)[:6])}"
                  f"{' ...' if len(bare) > 6 else ''}")
        return 0
