#!/usr/bin/env python3
"""Write si/example_table.typ from scripts/example_data.csv.

THIS IS THE TEMPLATE FOR THE si/ CONTRACT. Copy it for every table whose numbers
come out of an analysis. The rules that make the contract worth following:

  1. The script owns the file. It writes si/<name>.typ from scratch every run.
  2. The first line of the output is the "AUTO-GENERATED ... do not edit by hand"
     header, so anyone who opens it knows their edit will be overwritten.
  3. The output is a bare `#table(...)` and nothing else. It carries no caption
     and no label -- si-body.typ wraps it in a `#figure` and supplies those, so
     the prose keeps control of the numbering and the cross-reference.
  4. It reads from the analysis output, not from a value typed into the script.
     A number that only exists in the manuscript is a number nobody can check.

`just assets` (in analysis/) runs every scripts/gen_*_table.py, so a new table
needs no wiring beyond matching the filename pattern.
"""
from __future__ import annotations

import csv
from pathlib import Path

from _assets import record

HERE = Path(__file__).resolve().parent
SRC = HERE / "example_data.csv"
PAPER = HERE.parent.parent          # analysis/scripts/ -> analysis/ -> paper/
OUT = PAPER / "si" / "example_table.typ"

HEADER = f"// AUTO-GENERATED by scripts/{Path(__file__).name} -- do not edit by hand.\n"


def cell(text: str) -> str:
    """Escape a value for Typst content and wrap it in brackets."""
    for ch in ("\\", "[", "]", "#", "$", "*", "_", "@", "<", ">"):
        text = text.replace(ch, "\\" + ch)
    return f"[{text}]"


def main() -> int:
    with SRC.open(newline="") as fh:
        rows = list(csv.reader(fh))
    head, body = rows[0], rows[1:]

    # Right-align everything numeric, left-align the label column.
    align = ["left"] + ["right"] * (len(head) - 1)

    lines = [
        HEADER,
        "#table(\n",
        f"  columns: {len(head)},\n",
        f"  align: ({', '.join(align)}),\n",
        "  table.header(\n",
    ]
    # Prettify the CSV header: ci_low -> "CI low", n -> "$n$".
    pretty = {"n": "$n$", "ci_low": "CI low", "ci_high": "CI high"}
    labels = [pretty.get(h, h.replace("_", " ").capitalize()) for h in head]
    lines.append("    " + ", ".join(f"[{lbl}]" for lbl in labels) + ",\n")
    lines.append("  ),\n")

    for row in body:
        lines.append("  " + ", ".join(cell(v) for v in row) + ",\n")
    lines.append(")\n")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(lines))
    record("tbl.example", str(OUT.relative_to(PAPER)), kind="table",
           inputs=[str(SRC.relative_to(PAPER))],
           desc="Per-condition observed and expected values")
    print(f"wrote {OUT.relative_to(PAPER)}  ({len(body)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
