"""The toolchain package: `paper sync`, `paper sync --check` and `paper migrate`.

sync and check run against this checkout's package data (the editable
install), in a throwaway paper. migrate runs against a throwaway scaffold
repository with one tagged release, so the classification is exact: a
customized toolchain file is refused and nothing changes; a pristine paper is
moved onto the package and then passes `paper sync --check`.
"""
from __future__ import annotations

import contextlib
import io
import json
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tools"))

from paper_scaffold import data_dir, sync as sm, version  # noqa: E402
from paper_scaffold import migrate as mg  # noqa: E402

IDENT = ["-c", "user.name=t", "-c", "user.email=t@example.invalid",
         "-c", "commit.gpgsign=false", "-c", "tag.gpgsign=false"]
PIN = "paper-scaffold @ file:///nowhere"


def sh(cwd: Path, *args: str) -> None:
    subprocess.run(["git", *IDENT, *args], cwd=cwd, check=True, capture_output=True)


def write(root: Path, files: dict[str, str | bytes]) -> None:
    for rel, text in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(text, bytes):
            p.write_bytes(text)
        else:
            p.write_text(text)


def word_template(style: dict, italic_heading: bool = False) -> bytes:
    """A reference document as a paper would have held one: generated from
    `style`, optionally with an edit no [word.style] setting expresses."""
    import zipfile
    from paper_word_reference import generate
    with tempfile.TemporaryDirectory() as tmp:
        path = generate(Path(tmp) / "t.docx", style)
        if italic_heading:
            with zipfile.ZipFile(path) as z:
                parts = {n: z.read(n) for n in z.namelist()}
            xml = parts["word/styles.xml"].decode()
            at = xml.index('w:styleId="Heading2"')
            rpr = xml.index("<w:rPr>", at) + len("<w:rPr>")
            parts["word/styles.xml"] = (xml[:rpr] + "<w:i/>" + xml[rpr:]).encode()
            with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
                for n, b in parts.items():
                    z.writestr(n, b)
        return path.read_bytes()


# The template a 3.26.x paper was given: pandoc's blue headings.
OLD_BLUE = {"heading_color": "0F4761", "title_color": "0F4761"}


def paper(d: Path) -> Path:
    root = d / "paper"
    write(root, {"pyproject.toml": f'[project]\nname = "p"\ndependencies = ["{PIN}"]\n',
                 "paper.typ": "prose\n"})
    return root


def has(problems: list[str], *words: str) -> bool:
    return any(all(w in p for w in words) for p in problems)


def sync_cases(check) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = paper(Path(tmp))
        result = sm.sync(root)
        lock = json.loads((root / sm.LOCK).read_text())
        check("sync writes the always-generated files",
              all((root / f).is_file() for f in sm.ALWAYS), result.written)
        check("generated files carry the header",
              "GENERATED by `paper sync`" in (root / "stats.typ").read_text())
        check("lock records release, pin and every file",
              lock["scaffold"] == {"version": version(), "pin": PIN}
              and set(lock["files"]) == set(sm.ALWAYS), lock)
        check("docs mirrored", (root / sm.DOCS_MIRROR / "package.md").is_file())
        check("no analysis/ means no helpers", not (root / "analysis").exists())
        check("a fresh sync passes --check", sm.check(root) == [], sm.check(root))
        again = sm.sync(root)
        check("a second sync writes nothing", again.written == [], again.written)

        # An edit to a generated file: --check names it, sync refuses it.
        jf = root / "justfile"
        jf.write_text(jf.read_text() + "\nmine:\n  echo local\n")
        problems = sm.check(root)
        check("--check flags an edited generated file",
              has(problems, "justfile", "edited"), problems)
        try:
            sm.sync(root)
            check("sync refuses to overwrite an edit", False)
        except sm.SyncError as e:
            check("sync refuses to overwrite an edit", "justfile" in str(e), e)
        check("a refused sync leaves the edit", "echo local" in jf.read_text())
        sm.sync(root, force=True)
        check("--force restores the stock file", "echo local" not in jf.read_text()
              and sm.check(root) == [])

        # Missing file, version drift, a leftover toolchain directory.
        (root / "stats.typ").unlink()
        check("--check flags a missing generated file",
              has(sm.check(root), "stats.typ", "missing"))
        sm.sync(root)
        lock = json.loads((root / sm.LOCK).read_text())
        lock["scaffold"]["version"] = "0.0.1"
        (root / sm.LOCK).write_text(json.dumps(lock))
        check("--check flags a lock from another release",
              has(sm.check(root), "0.0.1", "run `uv run paper sync`"))
        sm.sync(root)
        (root / "tools").mkdir()
        (root / "tools" / "x.py").write_text("x = 1\n")
        check("--check flags a leftover tools/", has(sm.check(root), "tools/"))
        (root / "tools" / "x.py").unlink()
        (root / "tools").rmdir()

        # An override is the paper's: never written, never flagged, and wins.
        import paths
        check("without one the package's copy is used",
              paths.locate(root, "word/reference.docx")
              == paths.DATA / "word/reference.docx")
        write(root, {"word/reference.docx": "journal styled\n"})
        sm.sync(root)
        lock = json.loads((root / sm.LOCK).read_text())
        check("an override is listed in the lock",
              "word/reference.docx" in lock["overrides"], lock["overrides"])
        check("an override is not flagged", sm.check(root) == [], sm.check(root))
        check("an override wins over the package's copy",
              paths.locate(root, "word/reference.docx")
              == root / "word/reference.docx")
        check("the package ships no single-paper reference document (3.27.0)",
              not (paths.DATA / "word/paper-reference.docx").exists())
        (root / "word/reference.docx").unlink()

        # Optional features: written when present, removed when dropped.
        write(root, {"audio/config.py": "VOICE_NAME = 'x'\n",
                     "analysis/scripts/gen_stats.py": "pass\n"})
        sm.sync(root)
        check("audio scripts written with audio/config.py",
              all((root / f).is_file() for f in sm.AUDIO))
        check("analysis helpers and _toolchain written",
              (root / sm.TOOLCHAIN_DIR / "paths.py").is_file()
              and (root / "analysis/scripts/_stats.py").is_file())
        (root / "audio/config.py").unlink()
        removed = sm.sync(root).removed
        check("a dropped feature's generated files are removed",
              sorted(removed) == sorted(sm.AUDIO), removed)

    with tempfile.TemporaryDirectory() as tmp:
        root = paper(Path(tmp))
        write(root, {"justfile": "local:\n  echo mine\n"})
        try:
            sm.sync(root)
            check("sync refuses a file it never wrote", False)
        except sm.SyncError as e:
            check("sync refuses a file it never wrote",
                  "not written by paper sync" in str(e), e)
        check("--check on a paper with no lock says so",
              has(sm.check(root), "no .paper/scaffold.lock.json"))

    check("the scaffold checkout has nothing to sync", sm.check(data_dir()) == [])


NEW_PAPER = """#!/usr/bin/env bash
tar -C "$SCAFFOLD" -cf - --exclude='./.git' --exclude='./scripts' . | tar -C "$DEST" -xf -
"""
V1 = {
    "scripts/new-paper.sh": NEW_PAPER,
    "HISTORY.md": "# History\n\n---\n\n## 1.0.0\n\nFirst.\n",
    "pyproject.toml": '[project]\nname = "paper-scaffold"\nversion = "1.0.0"\n'
                      'dependencies = ["rich"]\n',
    "justfile": "paper:\n  echo build\n",
    "stats.typ": "// stats\n",
    "paper.typ": "placeholder\n",
    "tools/x.py": "x = 1\n",
    "tests/run.py": "pass\n",
    "docs/README.md": "docs\n",
    "journals/j.toml": "[journal]\n",
}


_STOCK: list[bytes] = []


def STOCK_TEMPLATE() -> bytes:  # the release's copy, generated once
    if not _STOCK:
        _STOCK.append(word_template(OLD_BLUE))
    return _STOCK[0]


def migrate_fixture(d: Path, edits: dict) -> tuple[Path, Path]:
    scaffold, project = d / "paper-scaffold", d / "proj"
    write(scaffold, {**V1, "word/paper-reference.docx": STOCK_TEMPLATE()})
    sh(scaffold, "init", "-q")
    sh(scaffold, "add", "-A")
    sh(scaffold, "commit", "-q", "-m", "v1")
    sh(scaffold, "tag", "-a", "v1.0.0", "-m", "v1")
    write(project, {k: v for k, v in V1.items() if not k.startswith("scripts/")})
    write(project, {"word/paper-reference.docx": STOCK_TEMPLATE()})
    write(project, {"pyproject.toml": '[project]\nname = "proj"\nversion = "1.0.0"\n'
                                      'dependencies = ["rich", "scipy"]\n',
                    "paper.typ": "real prose\n", **edits})
    sh(project, "init", "-q")
    sh(project, "add", "-A")
    sh(project, "commit", "-q", "-m", "paper")
    return scaffold, project


def quiet_main(*args) -> int:
    with contextlib.redirect_stdout(io.StringIO()), \
            contextlib.redirect_stderr(io.StringIO()):
        return mg.main(*args)


def migrate_cases(check) -> None:
    # A customized toolchain file, and one the scaffold never had: refused,
    # and nothing moves.
    with tempfile.TemporaryDirectory() as tmp:
        scaffold, project = migrate_fixture(Path(tmp), {
            "tools/x.py": "x = 'mine'\n", "tools/mine.py": "m = 1\n"})
        plan = mg.classify(project, scaffold, None, PIN)
        check("migrate refuses a customized tool",
              any(r.startswith("tools/x.py: customized") for r in plan.refused),
              plan.refused)
        check("migrate refuses a tool the scaffold never had",
              any(r.startswith("tools/mine.py") for r in plan.refused), plan.refused)
        rc = quiet_main(project, scaffold, None, PIN, False, False)
        check("a refusal exits 1", rc == 1, rc)
        check("a refusal changes nothing",
              (project / "tools/x.py").read_text() == "x = 'mine'\n"
              and (project / "tools/mine.py").is_file()
              and (project / "tests/run.py").is_file()
              and not (project / sm.LOCK).exists()
              and "paper-scaffold" not in (project / "pyproject.toml").read_text())

    # A customized justfile (paper sync now writes it): refused too.
    with tempfile.TemporaryDirectory() as tmp:
        scaffold, project = migrate_fixture(Path(tmp), {
            "justfile": "paper:\n  echo local build\n"})
        plan = mg.classify(project, scaffold, None, PIN)
        check("migrate refuses a customized generated file",
              any(r.startswith("justfile: customized") for r in plan.refused),
              plan.refused)

    # Pristine toolchain, customized journal profile, and a reference
    # document only recoloured black (what the 3.27.0 stock now is): migrates.
    with tempfile.TemporaryDirectory() as tmp:
        scaffold, project = migrate_fixture(Path(tmp), {
            "journals/j.toml": "[journal]\nmine = 1\n",
            "word/paper-reference.docx": word_template({})})
        plan = mg.classify(project, scaffold, None, PIN)
        check("a pristine paper has no refusals", plan.refused == [], plan.refused)
        check("the customized journal profile stays as an override",
              plan.overrides == ["journals/j.toml"], plan.overrides)
        check("a black-only reference document is removed",
              "word/paper-reference.docx" in plan.remove
              and plan.project_toml is None, (plan.remove, plan.word_note))
        check("extra dependencies are kept", plan.extra_deps == ["scipy"],
              plan.extra_deps)
        rc = quiet_main(project, scaffold, None, PIN, False, False)
        check("migrate exits 0", rc == 0, rc)
        check("toolchain directories removed",
              not any((project / d).exists() for d in ("tools", "tests", "docs")))
        check("pristine HISTORY and the old template removed",
              not (project / "HISTORY.md").exists()
              and not (project / "word/paper-reference.docx").exists())
        check("override kept",
              (project / "journals/j.toml").read_text() == "[journal]\nmine = 1\n")
        py = (project / "pyproject.toml").read_text()
        check("pyproject pins the package", PIN in py and '"scipy"' in py, py)
        check("paper prose untouched",
              (project / "paper.typ").read_text() == "real prose\n")
        check("the migrated paper passes --check", sm.check(project) == [],
              sm.check(project))
        check(".paper/docs/ ignored",
              ".paper/docs/" in (project / ".gitignore").read_text())
        try:
            mg.classify(project, scaffold, None, PIN)
            check("a second migrate is refused", False)
        except mg.MigrateError as e:
            check("a second migrate is refused", "already has" in str(e), e)

    import project_hooks as ph

    # The untouched old template (blue headings): removed, nothing added.
    with tempfile.TemporaryDirectory() as tmp:
        scaffold, project = migrate_fixture(Path(tmp), {})
        plan = mg.classify(project, scaffold, None, PIN)
        check("the stock old template is removed",
              "word/paper-reference.docx" in plan.remove and plan.project_toml is None,
              plan.remove)

    # Edits [word.style] expresses: removed, the block goes into project.toml.
    with tempfile.TemporaryDirectory() as tmp:
        scaffold, project = migrate_fixture(Path(tmp), {
            "word/paper-reference.docx": word_template(
                {"heading_color": "000000", "title_color": "000000",
                 "title_size": 20, "title_align": "left"}),
            "project.toml": "schema_version = 1\n\n[word]\nlua_filters = []\n"})
        plan = mg.classify(project, scaffold, None, PIN)
        check("an expressible template has no refusals", plan.refused == [],
              plan.refused)
        rc = quiet_main(project, scaffold, None, PIN, False, False)
        check("migrate with [word.style] exits 0", rc == 0, rc)
        style = ph.load(project).word.style
        check("project.toml gets the paper's own edits, not the old blue",
              style == {"title_size": 20, "title_align": "left"}, style)
        check("the translated template is removed",
              not (project / "word/paper-reference.docx").exists())
        check("its build inputs are clean", ph.build_inputs(project) == ["project.toml"],
              ph.build_inputs(project))

    # Edits no setting expresses: kept and declared as [word] reference.
    with tempfile.TemporaryDirectory() as tmp:
        data = word_template(OLD_BLUE, italic_heading=True)
        scaffold, project = migrate_fixture(Path(tmp), {
            "word/paper-reference.docx": data})
        rc = quiet_main(project, scaffold, None, PIN, False, False)
        check("migrate with [word] reference exits 0", rc == 0, rc)
        word = ph.load(project).word
        check("the template is declared as [word] reference",
              word.reference == "word/paper-reference.docx" and not word.style,
              (word.reference, word.style))
        check("the declared template is kept as it was",
              (project / "word/paper-reference.docx").read_bytes() == data)
        check("the migrated paper passes --check", sm.check(project) == [],
              sm.check(project))

    # A customized HISTORY.md is refused: from 4.0.0 it is the package's.
    with tempfile.TemporaryDirectory() as tmp:
        scaffold, project = migrate_fixture(Path(tmp), {
            "HISTORY.md": "# History\n\nOur own notes.\n"})
        plan = mg.classify(project, scaffold, None, PIN)
        check("a customized HISTORY.md is refused",
              any(r.startswith("HISTORY.md") and "PROJECT-HISTORY" in r
                  for r in plan.refused), plan.refused)

    # Adding [word] reference into an existing [word] table.
    text = mg.word_table("schema_version = 1\n[word]\nlua_filters = []\n", None)
    check("reference is inserted into an existing [word] table",
          'reference = "word/paper-reference.docx"' in text
          and text.count("[word]") == 1, text)


def run_cases() -> bool:
    ok = True

    def check(name: str, cond: bool, detail: object = "") -> None:
        nonlocal ok
        if not cond:
            print(f"  package [{name}]: failed {detail}")
            ok = False

    sync_cases(check)
    migrate_cases(check)
    return ok


if __name__ == "__main__":
    raise SystemExit(0 if run_cases() else 1)
