"""The journal upload set: split outputs, the standalone graphic, the letter.

What this guards: the Word projection splits at exactly one SI heading or
refuses; the graphical abstract is written in the profile's format, flattened,
and measures inside the journal's box or fails on the resolution floor; a
profile names only a format this can write; the submission placement defaults
to the journal layout; a missing <si-start> probe is a clear error, not a
wrong page range; an absent cover-letter.typ is tolerated and leaves no stale
letter behind; the letter's words and pages are measured, recorded, and
held to the profile's [cover-letter] limits by check-submission only; a paper with no SI or a separate SI target ships the right
set; an SI citing the main list gets its own local list and qualified
main-text references; a recorded output reads stale when its source moves;
and a captured build's tools import nothing the capture leaves out.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
import unittest
import unittest.mock
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import journal
from journal_cases import PROFILE
from PIL import Image

import submission

HEADING = "#heading(level: 1, numbering: none, outlined: false)[Supporting Information]"
WORD = f"""// GENERATED by tools/resolve_typst.py -- do not edit.
// second header line

= Title

Main text.

#bibliography("references.bib")

{HEADING}

SI text.
"""


class SubmissionCases(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        (self.root / ".build-state").mkdir()

    def tearDown(self):
        self.tmp.cleanup()

    def put(self, name: str, text: str) -> Path:
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        return path

    # --- Word split ----------------------------------------------------------

    def test_word_projection_splits_once_at_the_si_heading(self):
        main, si = submission.split_word_source(WORD)
        self.assertIn("Main text.", main)
        self.assertIn("#bibliography", main)
        self.assertNotIn("SI text.", main)
        self.assertNotIn("Supporting Information]", main)
        self.assertTrue(si.startswith("// GENERATED"))
        self.assertIn(HEADING, si)
        self.assertNotIn("Main text.", si)

    def test_word_split_refuses_zero_or_two_si_headings(self):
        for text in (WORD.replace(HEADING, ""), WORD + "\n" + HEADING + "\n"):
            with self.assertRaisesRegex(submission.SubmissionError, "one Supporting"):
                submission.split_word_source(text)

    # --- graphical abstract --------------------------------------------------

    def test_graphic_is_flattened_and_fits_the_box(self):
        src = self.root / "toc.png"
        Image.new("RGBA", (975, 525), (0, 0, 0, 0)).save(src, dpi=(72, 72))
        spec = {"width-in": 3.25, "height-in": 1.75, "min-dpi": 300}
        info = submission.export_graphic(src, self.root / "toc-graphic.tif", spec)
        self.assertEqual(info, {"format": "tif", "dpi": 300, "pixels": [975, 525]})
        out = Image.open(self.root / "toc-graphic.tif")
        self.assertEqual(out.mode, "RGB")
        self.assertEqual(out.getpixel((0, 0)), (255, 255, 255))
        self.assertAlmostEqual(out.info["dpi"][0], 300, places=0)
        # A wider source sets the resolution from its binding dimension.
        Image.new("RGB", (1950, 700)).save(src)
        info = submission.export_graphic(src, self.root / "toc-graphic.png", spec)
        self.assertEqual((info["format"], info["dpi"]), ("png", 600))

    def test_graphic_below_the_floor_fails(self):
        src = self.root / "small.png"
        Image.new("RGB", (300, 160)).save(src)
        spec = {"width-in": 3.25, "height-in": 1.75, "min-dpi": 300}
        with self.assertRaisesRegex(submission.SubmissionError, "floor is 300 dpi"):
            submission.export_graphic(src, self.root / "toc-graphic.tif", spec)

    def test_profile_file_format_is_validated(self):
        self.put("journals/ok.toml", PROFILE + 'file-format = "tif"\n')
        self.assertEqual(journal.load_profile(self.root, "ok").graphic["file-format"], "tif")
        self.put("journals/bad.toml", PROFILE + 'file-format = "eps"\n')
        with self.assertRaisesRegex(journal.JournalError, "file-format"):
            journal.load_profile(self.root, "bad")

    def test_submission_placement_defaults_to_the_journal_layout(self):
        self.put("journal.toml", 'schema_version = 1\nprofile = ""\n')
        self.assertEqual(journal.placement(self.root, "submission"), "journal")
        self.put("journal.toml", 'schema_version = 1\nprofile = ""\n'
                                 '[placement]\nsubmission = "none"\n')
        self.assertEqual(journal.placement(self.root, "submission"), "none")

    # --- split PDFs ------------------------------------------------------------

    @unittest.skipUnless(shutil.which("typst"), "typst not installed")
    def test_missing_si_probe_is_a_clear_error(self):
        self.put("paper.typ", "Main.\n#pagebreak()\nSI.\n")
        with self.assertRaisesRegex(submission.SubmissionError, "no <si-start> probe"):
            submission.si_start(self.root, "journal")
        self.put("paper.typ", "Main.\n#pagebreak()\n"
                              "#context [#metadata(here().page()) <si-start>]\nSI.\n")
        self.assertEqual(submission.si_start(self.root, "journal"), 2)

    # --- where the SI lives ----------------------------------------------------

    def fake_capture(self, paper: str, word: str) -> Path:
        """A sealed-looking capture of `paper` whose Word projection is `word`."""
        self.put("paper.typ", paper)
        folder = self.root / ".build-state" / "manuscripts" / "cap"
        folder.mkdir(parents=True)
        (folder / "paper.typ").write_text(paper)
        (folder / "paper.word.typ").write_text(word)
        self.put(".build-state/manuscript.json", json.dumps(
            {"id": "cap" * 8, "path": ".build-state/manuscripts/cap"}))
        self.put("journal.toml", 'schema_version = 1\nprofile = ""\n')
        # Records hash the running tool; check reads root/tools/submission.py.
        self.put("tools/submission.py", (ROOT / "tools/submission.py").read_text())
        self.reseal()
        return folder

    def reseal(self) -> None:
        """Record the tree as it is now as the capture's sources."""
        from build_state import snapshot
        deps = ["paper.typ"]
        (self.root / ".build-state/manuscripts/cap/manifest.json").write_text(json.dumps({
            "schema_version": 1, "id": "cap" * 8, "files": {}, "dependencies": deps,
            "sources": snapshot(self.root, deps)}))

    SEPARATE = """schema_version = 1
default_document = "main"
[parts.main]
source = "paper.typ"
[parts.si]
source = "si-body.typ"
[documents.main]
entrypoint = "paper.typ"
output = "build/main.pdf"
parts = ["main"]
[documents.supplement]
entrypoint = "si.typ"
output = "build/si.pdf"
parts = ["si"]
"""
    BODY = "// >>> BODY START\n{}\n// <<< BODY END\n"

    def test_si_layout_reads_the_capture_and_manuscript_toml(self):
        folder = self.fake_capture("Main.\n", WORD)
        self.assertEqual(submission.si_layout(self.root, folder), ("appendix", None))
        (folder / "paper.word.typ").write_text(WORD.replace(HEADING, ""))
        self.assertEqual(submission.si_layout(self.root, folder), ("none", None))
        # A separate SI target is found by the part it carries, not its name.
        self.put("paper.typ", self.BODY.format("Main."))
        self.put("si-body.typ", self.BODY.format("SI."))
        self.put("si.typ", '#include "si-body.typ"\n')
        self.put("manuscript.toml", self.SEPARATE)
        self.assertEqual(submission.si_layout(self.root, folder), ("separate", "si.typ"))

    @unittest.skipUnless(shutil.which("typst"), "typst not installed")
    def test_a_manuscript_without_si_ships_main_only(self):
        # exclusionms-paper: no si-body include, so no <si-start> and no SI
        # heading. The main file is the whole PDF; the si-* steps note, write
        # nothing, and clear a stale SI file; check agrees with the set.
        self.fake_capture("Main text.\n", WORD.replace(HEADING, "").replace("SI text.", ""))
        self.put("submission/supporting-information.pdf", "stale")
        submission.save_records(self.root, {"supporting-information.pdf": {
            "kind": "files", "sources": {}, "output_hash": "x"}})
        self.reseal()
        self.assertIn("whole manuscript", submission.split_pdf(self.root, "main-pdf"))
        for kind in ("si-pdf", "si-docx"):
            self.assertIn("no Supporting Information", submission.split_pdf(self.root, kind)
                          if kind == "si-pdf" else submission.split_docx(self.root, kind))
        self.assertFalse((self.root / "submission/supporting-information.pdf").exists())
        self.assertEqual(submission.check(self.root), [
            {"output": "submission/manuscript.pdf", "status": "current"}])
        records = submission.load_records(self.root)
        self.assertEqual((records["manuscript.pdf"]["pages"], records["manuscript.pdf"]["si"]),
                         ("1-", "none"))
        manifest = json.loads((self.root / "submission/manifest.json").read_text())
        self.assertIn("no Supporting Information", manifest["note"])

    @unittest.skipUnless(shutil.which("typst"), "typst not installed")
    def test_a_separate_si_target_is_the_si_pdf_and_has_no_word_file(self):
        # cascade/paper: the SI is manuscript.toml's second document target.
        self.fake_capture(self.BODY.format("Main."), WORD.replace(HEADING, ""))
        self.put("si-body.typ", self.BODY.format("SI body."))
        self.put("si.typ", '#include "si-body.typ"\n')
        self.put("manuscript.toml", self.SEPARATE)
        self.put("tools/render_stats.py", "")
        self.reseal()
        self.assertIn("whole manuscript", submission.split_pdf(self.root, "main-pdf"))
        self.assertIn("separate SI target si.typ", submission.split_pdf(self.root, "si-pdf"))
        self.assertIn("no submission/supporting-information.docx",
                      submission.split_docx(self.root, "si-docx"))
        rows = {r["output"]: r["status"] for r in submission.check(self.root)}
        self.assertEqual(rows, {"submission/manuscript.pdf": "current",
                                "submission/supporting-information.pdf": "current"})
        # The SI PDF is recorded by what it read: an SI edit makes it stale.
        self.put("si-body.typ", self.BODY.format("SI body, edited."))
        rows = {r["output"]: r["status"] for r in submission.check(self.root)}
        self.assertEqual(rows["submission/supporting-information.pdf"], "stale")

    # --- an SI that cites the main reference list -----------------------------

    BIB = ('@article{alpha, title={Alpha Work}, author={Aa, B}, year={2020}, journal={J}}\n'
           '@article{beta, title={Beta Work}, author={Bb, C}, year={2021}, journal={J}}\n'
           '@article{gamma, title={Gamma Work}, author={Cc, D}, year={2022}, journal={J}}\n')
    MAIN_BIB = '#bibliography("references.bib", title: [References], style: "american-chemical-society")'

    def single_list_word(self, si: str) -> str:
        return WORD.replace('#bibliography("references.bib")', self.MAIN_BIB) \
                   .replace("SI text.", si)

    def test_main_text_references_are_qualified_in_the_si(self):
        q = submission.qualify_main_text_references
        self.assertEqual(q("as in Figure 3; Figures 2 and 3 agree."),
                         "as in Figure 3 of the main text; Figures 2 and 3 of the main text agree.")
        self.assertEqual(q("Section 2.3 and Section 2.4 set it."),
                         "Section 2.3 and Section 2.4 of the main text set it.")
        self.assertEqual(q("Table 12a lists it."), "Table 12a of the main text lists it.")
        # S-numbered, caption labels, already qualified, comments and strings: untouched.
        for text in ("Figure S3 shows it.", "Table S2: sizes", "Figure 3: caption",
                     "Figure 5 in the main text.", "Figure 5 of the main text.",
                     "// Figure 3 is a note", '#image("Figure 3.png")'):
            self.assertEqual(q(text), text)

    def test_standalone_si_only_when_the_si_cites_the_main_list(self):
        # The SI cites nothing: the page-range split stands.
        self.assertIsNone(submission.standalone_si(self.single_list_word("SI text.")))
        # A si- list of its own (the resolver writes its #bibliography): unchanged.
        own = self.single_list_word('See @si-x.\n\n#bibliography("si.bib", title: [SI References])')
        self.assertIsNone(submission.standalone_si(own))
        st = submission.standalone_si(self.single_list_word("See @gamma and Figure 2."))
        self.assertEqual(st.keys, {"gamma"})
        self.assertIn("Figure 2 of the main text.", st.text)
        self.assertTrue(st.text.rstrip().endswith(self.MAIN_BIB))
        self.assertNotIn("Main text.", st.text)

    @unittest.skipUnless(shutil.which("typst"), "typst not installed")
    def test_a_single_list_si_gets_a_local_reference_list(self):
        # spectrl-paper, uno-paper, koth-lfq-paper: the SI cites main-list keys.
        word = self.single_list_word("SI cites @gamma.")
        folder = self.fake_capture(
            "Main cites @alpha and @beta.\n#pagebreak()\n"
            "#context [#metadata(here().page()) <si-start>]\nSI.\n", word)
        (folder / "references.bib").write_text(self.BIB)
        self.assertIn("local reference list of 1 works",
                      submission.split_pdf(self.root, "si-pdf"))
        record = submission.load_records(self.root)["supporting-information.pdf"]
        self.assertEqual(record["si"], "standalone")
        self.assertEqual(list(folder.glob(".submission-si-*")), [])
        manifest = json.loads((self.root / "submission/manifest.json").read_text())
        self.assertIn("local reference list", manifest["note"])
        # The list itself: only what the SI cites, numbered from 1.
        (folder / "si.typ").write_text(submission.standalone_si(word).text)
        subprocess.run(["typst", "compile", "--root", str(folder), "--features", "html",
                        "--format", "html", str(folder / "si.typ"), str(folder / "si.html")],
                       check=True, capture_output=True)
        html = (folder / "si.html").read_text()
        self.assertIn("Gamma Work", html)
        self.assertNotIn("Alpha Work", html)
        self.assertIn("(1)", html)

    def test_split_refuses_without_a_captured_manuscript(self):
        with self.assertRaisesRegex(submission.SubmissionError, "just paper"):
            submission.capture(self.root)

    # --- cover letter and records ----------------------------------------------

    def test_absent_cover_letter_is_tolerated_and_clears_a_stale_one(self):
        self.put("submission/cover-letter.pdf", "old")
        submission.save_records(self.root, {"cover-letter.pdf": {
            "kind": "files", "sources": {}, "output_hash": "x"}})
        note = submission.cover_letter(self.root)
        self.assertIn("no cover-letter.typ", note)
        self.assertFalse((self.root / "submission/cover-letter.pdf").exists())
        self.assertEqual(submission.load_records(self.root), {})

    def _letter_profile(self, limits: str) -> None:
        self.put("journals/test-article.toml", PROFILE + "[cover-letter]\n" + limits)
        self.put("journal.toml", 'schema_version = 1\nprofile = "test-article"\n'
                                 '[sections]\nmethods = "main/Methods"\n')

    def _record_letter(self, **counts) -> None:
        self.put("cover-letter.typ", "Dear Editors,\n")
        staged = self.put("staged.pdf", "pdf")
        sources = submission.file_sources(self.root, ["cover-letter.typ"])
        sources["tools/submission.py"] = submission.tool_digest()
        submission.publish(self.root, staged, "cover-letter.pdf",
                           {"kind": "files", "sources": sources, **counts})

    def test_cover_letter_over_the_profiles_limit_fails_check_submission(self):
        self._letter_profile("max-words = 400\nmax-pages = 1\n")
        self._record_letter(words=401, pages=2)
        self.assertEqual(len(submission.letter_limits(self.root)), 2)
        self.assertEqual(submission.main(["check", "--root", str(self.root)]), 1)
        # `just check` runs it with --note: reported, never failed.
        self.assertEqual(submission.main(["check", "--note", "--root", str(self.root)]), 0)
        manifest = json.loads((self.root / "submission/manifest.json").read_text())
        self.assertEqual(manifest["files"]["cover-letter.pdf"]["words"], 401)
        self._record_letter(words=400, pages=1)
        self.assertEqual(submission.letter_limits(self.root), [])
        self.assertEqual(submission.main(["check", "--root", str(self.root)]), 0)

    def test_no_letter_and_no_letter_rules_are_both_tolerated(self):
        # A profile limit with no letter built: nothing to check.
        self._letter_profile("max-words = 10\n")
        self.assertEqual(submission.letter_limits(self.root), [])
        # A letter with no [cover-letter] table: counted, never limited.
        self.put("journals/test-article.toml", PROFILE)
        self._record_letter(words=10**5, pages=40)
        self.assertEqual(submission.letter_limits(self.root), [])

    @unittest.skipUnless(shutil.which("typst"), "typst not installed")
    def test_cover_letter_build_measures_words_and_pages(self):
        self._letter_profile("max-words = 5\n")
        self.put("cover-letter.typ", "#set page(height: 3in)\nDear Editors of "
                 "#sys.inputs.at(\"journal\"), one two three.\n#pagebreak()\nSincerely,\n")
        with unittest.mock.patch.object(submission, "tool",
                                        lambda name: ROOT / "tools" / name):
            try:
                message = submission.cover_letter(self.root)
            except subprocess.CalledProcessError as exc:
                self.skipTest(f"typst could not compile the letter here: {exc}")
        record = submission.load_records(self.root)["cover-letter.pdf"]
        self.assertEqual(record["pages"], 2)
        if record["words"] is None:
            self.skipTest("wordometer is not in the Typst package cache")
        self.assertEqual(record["words"], 10)   # "Journal of Tests" is three
        self.assertIn("10 words, 2 page(s)", message)
        self.assertIn("LIMIT:", message)
        self.assertFalse(list(self.root.glob(".cover-letter-count-*")))

    def test_recorded_output_goes_stale_and_replaced(self):
        # The record hashes the running tool (tools/paths.py), wherever it is.
        self.put("cover-letter.typ", "Dear Editors,\n")
        staged = self.put("staged.pdf", "pdf")
        sources = submission.file_sources(self.root, ["cover-letter.typ"])
        sources["tools/submission.py"] = submission.tool_digest()
        submission.publish(self.root, staged, "cover-letter.pdf",
                           {"kind": "files", "sources": sources})
        rows = submission.check(self.root)
        self.assertEqual(rows, [{"output": "submission/cover-letter.pdf", "status": "current"}])
        manifest = json.loads((self.root / "submission/manifest.json").read_text())
        self.assertEqual(manifest["files"]["cover-letter.pdf"]["role"], "cover letter")
        self.put("cover-letter.typ", "Dear Editor,\n")
        self.assertEqual(submission.check(self.root)[0]["status"], "stale")
        self.put("cover-letter.typ", "Dear Editors,\n")
        self.put("submission/cover-letter.pdf", "edited by hand")
        self.assertEqual(submission.check(self.root)[0]["status"], "replaced")
        (self.root / "submission/cover-letter.pdf").unlink()
        self.assertEqual(submission.check(self.root)[0]["status"], "missing")
        # --note never fails; the strict check does.
        self.assertEqual(submission.main(["check", "--note", "--root", str(self.root)]), 0)
        self.assertEqual(submission.main(["check", "--root", str(self.root)]), 1)

    def test_captured_tools_import_only_captured_tools(self):
        """A captured build's tools run with nothing else on their path.

        4.1.0 captured export_docx.py but not the paths.py it imports, so
        `just main-docx` died with ModuleNotFoundError. Copy BUILD_TOOLS the
        way materialize() does, check every tools/ import (lazy ones too)
        resolves inside the copy, then run the copied export_docx.py alone.
        """
        import ast
        import os
        from build_state import BUILD_TOOLS
        from paths import locate
        tools = self.root / "captured" / "tools"
        tools.mkdir(parents=True)
        for name in BUILD_TOOLS:
            shutil.copyfile(locate(ROOT, f"tools/{name}"), tools / name)
        toolchain = {p.stem for p in (ROOT / "tools").glob("*.py")}
        captured = {p.stem for p in tools.glob("*.py")}
        for path in tools.glob("*.py"):
            for node in ast.walk(ast.parse(path.read_text())):
                if isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                    names = [node.module]
                elif isinstance(node, ast.Import):
                    names = [alias.name for alias in node.names]
                else:
                    continue
                for module in names:
                    module = module.split(".")[0]
                    if module in toolchain:
                        self.assertIn(module, captured, f"{path.name} imports {module}")
        env = {k: v for k, v in os.environ.items() if k != "PYTHONPATH"}
        run = subprocess.run([sys.executable, "-E", str(tools / "export_docx.py"), "--help"],
                             cwd=tools.parent, env=env, capture_output=True, text=True)
        self.assertEqual(run.returncode, 0, run.stderr)


def run_cases() -> bool:
    suite = unittest.defaultTestLoader.loadTestsFromTestCase(SubmissionCases)
    return unittest.TextTestRunner(verbosity=1).run(suite).wasSuccessful()


if __name__ == "__main__":
    raise SystemExit(0 if run_cases() else 1)
