"""The journal upload set: split outputs, the standalone graphic, the letter.

What this guards: the Word projection splits at exactly one SI heading or
refuses; the graphical abstract is written in the profile's format, flattened,
and measures inside the journal's box or fails on the resolution floor; a
profile names only a format this can write; the submission placement defaults
to the journal layout; a missing <si-start> probe is a clear error, not a
wrong page range; an absent cover-letter.typ is tolerated and leaves no stale
letter behind; and a recorded output reads stale when its source moves.
"""
from __future__ import annotations

import json
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import journal
from journal_cases import PROFILE
from PIL import Image

import submission

HEADING = "#heading(level: 1, numbering: none, outlined: false)[Supporting Information]"
WORD = f"""// GENERATED by tools/resolve_typst.py -- do not edit.
// second header line

= Title

Main text.

#bibliography("references.bib")

{HEADING}

SI text.
"""


class SubmissionCases(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        (self.root / ".build-state").mkdir()

    def tearDown(self):
        self.tmp.cleanup()

    def put(self, name: str, text: str) -> Path:
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        return path

    # --- Word split ----------------------------------------------------------

    def test_word_projection_splits_once_at_the_si_heading(self):
        main, si = submission.split_word_source(WORD)
        self.assertIn("Main text.", main)
        self.assertIn("#bibliography", main)
        self.assertNotIn("SI text.", main)
        self.assertNotIn("Supporting Information]", main)
        self.assertTrue(si.startswith("// GENERATED"))
        self.assertIn(HEADING, si)
        self.assertNotIn("Main text.", si)

    def test_word_split_refuses_zero_or_two_si_headings(self):
        for text in (WORD.replace(HEADING, ""), WORD + "\n" + HEADING + "\n"):
            with self.assertRaisesRegex(submission.SubmissionError, "one Supporting"):
                submission.split_word_source(text)

    # --- graphical abstract --------------------------------------------------

    def test_graphic_is_flattened_and_fits_the_box(self):
        src = self.root / "toc.png"
        Image.new("RGBA", (975, 525), (0, 0, 0, 0)).save(src, dpi=(72, 72))
        spec = {"width-in": 3.25, "height-in": 1.75, "min-dpi": 300}
        info = submission.export_graphic(src, self.root / "toc-graphic.tif", spec)
        self.assertEqual(info, {"format": "tif", "dpi": 300, "pixels": [975, 525]})
        out = Image.open(self.root / "toc-graphic.tif")
        self.assertEqual(out.mode, "RGB")
        self.assertEqual(out.getpixel((0, 0)), (255, 255, 255))
        self.assertAlmostEqual(out.info["dpi"][0], 300, places=0)
        # A wider source sets the resolution from its binding dimension.
        Image.new("RGB", (1950, 700)).save(src)
        info = submission.export_graphic(src, self.root / "toc-graphic.png", spec)
        self.assertEqual((info["format"], info["dpi"]), ("png", 600))

    def test_graphic_below_the_floor_fails(self):
        src = self.root / "small.png"
        Image.new("RGB", (300, 160)).save(src)
        spec = {"width-in": 3.25, "height-in": 1.75, "min-dpi": 300}
        with self.assertRaisesRegex(submission.SubmissionError, "floor is 300 dpi"):
            submission.export_graphic(src, self.root / "toc-graphic.tif", spec)

    def test_profile_file_format_is_validated(self):
        self.put("journals/ok.toml", PROFILE + 'file-format = "tif"\n')
        self.assertEqual(journal.load_profile(self.root, "ok").graphic["file-format"], "tif")
        self.put("journals/bad.toml", PROFILE + 'file-format = "eps"\n')
        with self.assertRaisesRegex(journal.JournalError, "file-format"):
            journal.load_profile(self.root, "bad")

    def test_submission_placement_defaults_to_the_journal_layout(self):
        self.put("journal.toml", 'schema_version = 1\nprofile = ""\n')
        self.assertEqual(journal.placement(self.root, "submission"), "journal")
        self.put("journal.toml", 'schema_version = 1\nprofile = ""\n'
                                 '[placement]\nsubmission = "none"\n')
        self.assertEqual(journal.placement(self.root, "submission"), "none")

    # --- split PDFs ------------------------------------------------------------

    @unittest.skipUnless(shutil.which("typst"), "typst not installed")
    def test_missing_si_probe_is_a_clear_error(self):
        self.put("paper.typ", "Main.\n#pagebreak()\nSI.\n")
        with self.assertRaisesRegex(submission.SubmissionError, "no <si-start> probe"):
            submission.si_start(self.root, "journal")
        self.put("paper.typ", "Main.\n#pagebreak()\n"
                              "#context [#metadata(here().page()) <si-start>]\nSI.\n")
        self.assertEqual(submission.si_start(self.root, "journal"), 2)

    # --- where the SI lives ----------------------------------------------------

    def fake_capture(self, paper: str, word: str) -> Path:
        """A sealed-looking capture of `paper` whose Word projection is `word`."""
        self.put("paper.typ", paper)
        folder = self.root / ".build-state" / "manuscripts" / "cap"
        folder.mkdir(parents=True)
        (folder / "paper.typ").write_text(paper)
        (folder / "paper.word.typ").write_text(word)
        self.put(".build-state/manuscript.json", json.dumps(
            {"id": "cap" * 8, "path": ".build-state/manuscripts/cap"}))
        self.put("journal.toml", 'schema_version = 1\nprofile = ""\n')
        # Records hash the running tool; check reads root/tools/submission.py.
        self.put("tools/submission.py", (ROOT / "tools/submission.py").read_text())
        self.reseal()
        return folder

    def reseal(self) -> None:
        """Record the tree as it is now as the capture's sources."""
        from build_state import snapshot
        deps = ["paper.typ"]
        (self.root / ".build-state/manuscripts/cap/manifest.json").write_text(json.dumps({
            "schema_version": 1, "id": "cap" * 8, "files": {}, "dependencies": deps,
            "sources": snapshot(self.root, deps)}))

    SEPARATE = """schema_version = 1
default_document = "main"
[parts.main]
source = "paper.typ"
[parts.si]
source = "si-body.typ"
[documents.main]
entrypoint = "paper.typ"
output = "build/main.pdf"
parts = ["main"]
[documents.supplement]
entrypoint = "si.typ"
output = "build/si.pdf"
parts = ["si"]
"""
    BODY = "// >>> BODY START\n{}\n// <<< BODY END\n"

    def test_si_layout_reads_the_capture_and_manuscript_toml(self):
        folder = self.fake_capture("Main.\n", WORD)
        self.assertEqual(submission.si_layout(self.root, folder), ("appendix", None))
        (folder / "paper.word.typ").write_text(WORD.replace(HEADING, ""))
        self.assertEqual(submission.si_layout(self.root, folder), ("none", None))
        # A separate SI target is found by the part it carries, not its name.
        self.put("paper.typ", self.BODY.format("Main."))
        self.put("si-body.typ", self.BODY.format("SI."))
        self.put("si.typ", '#include "si-body.typ"\n')
        self.put("manuscript.toml", self.SEPARATE)
        self.assertEqual(submission.si_layout(self.root, folder), ("separate", "si.typ"))

    @unittest.skipUnless(shutil.which("typst"), "typst not installed")
    def test_a_manuscript_without_si_ships_main_only(self):
        # exclusionms-paper: no si-body include, so no <si-start> and no SI
        # heading. The main file is the whole PDF; the si-* steps note, write
        # nothing, and clear a stale SI file; check agrees with the set.
        self.fake_capture("Main text.\n", WORD.replace(HEADING, "").replace("SI text.", ""))
        self.put("submission/supporting-information.pdf", "stale")
        submission.save_records(self.root, {"supporting-information.pdf": {
            "kind": "files", "sources": {}, "output_hash": "x"}})
        self.reseal()
        self.assertIn("whole manuscript", submission.split_pdf(self.root, "main-pdf"))
        for kind in ("si-pdf", "si-docx"):
            self.assertIn("no Supporting Information", submission.split_pdf(self.root, kind)
                          if kind == "si-pdf" else submission.split_docx(self.root, kind))
        self.assertFalse((self.root / "submission/supporting-information.pdf").exists())
        self.assertEqual(submission.check(self.root), [
            {"output": "submission/manuscript.pdf", "status": "current"}])
        records = submission.load_records(self.root)
        self.assertEqual((records["manuscript.pdf"]["pages"], records["manuscript.pdf"]["si"]),
                         ("1-", "none"))
        manifest = json.loads((self.root / "submission/manifest.json").read_text())
        self.assertIn("no Supporting Information", manifest["note"])

    @unittest.skipUnless(shutil.which("typst"), "typst not installed")
    def test_a_separate_si_target_is_the_si_pdf_and_has_no_word_file(self):
        # cascade/paper: the SI is manuscript.toml's second document target.
        self.fake_capture(self.BODY.format("Main."), WORD.replace(HEADING, ""))
        self.put("si-body.typ", self.BODY.format("SI body."))
        self.put("si.typ", '#include "si-body.typ"\n')
        self.put("manuscript.toml", self.SEPARATE)
        self.put("tools/render_stats.py", "")
        self.reseal()
        self.assertIn("whole manuscript", submission.split_pdf(self.root, "main-pdf"))
        self.assertIn("separate SI target si.typ", submission.split_pdf(self.root, "si-pdf"))
        self.assertIn("no submission/supporting-information.docx",
                      submission.split_docx(self.root, "si-docx"))
        rows = {r["output"]: r["status"] for r in submission.check(self.root)}
        self.assertEqual(rows, {"submission/manuscript.pdf": "current",
                                "submission/supporting-information.pdf": "current"})
        # The SI PDF is recorded by what it read: an SI edit makes it stale.
        self.put("si-body.typ", self.BODY.format("SI body, edited."))
        rows = {r["output"]: r["status"] for r in submission.check(self.root)}
        self.assertEqual(rows["submission/supporting-information.pdf"], "stale")

    def test_split_refuses_without_a_captured_manuscript(self):
        with self.assertRaisesRegex(submission.SubmissionError, "just paper"):
            submission.capture(self.root)

    # --- cover letter and records ----------------------------------------------

    def test_absent_cover_letter_is_tolerated_and_clears_a_stale_one(self):
        self.put("submission/cover-letter.pdf", "old")
        submission.save_records(self.root, {"cover-letter.pdf": {
            "kind": "files", "sources": {}, "output_hash": "x"}})
        note = submission.cover_letter(self.root)
        self.assertIn("no cover-letter.typ", note)
        self.assertFalse((self.root / "submission/cover-letter.pdf").exists())
        self.assertEqual(submission.load_records(self.root), {})

    def test_recorded_output_goes_stale_and_replaced(self):
        # The record hashes the running tool; point the tool path at this root.
        self.put("tools/submission.py", "# tool\n")
        self.put("cover-letter.typ", "Dear Editors,\n")
        staged = self.put("staged.pdf", "pdf")
        sources = submission.file_sources(self.root, ["cover-letter.typ"])
        sources["tools/submission.py"] = submission.digest(self.root / "tools/submission.py")
        submission.publish(self.root, staged, "cover-letter.pdf",
                           {"kind": "files", "sources": sources})
        rows = submission.check(self.root)
        self.assertEqual(rows, [{"output": "submission/cover-letter.pdf", "status": "current"}])
        manifest = json.loads((self.root / "submission/manifest.json").read_text())
        self.assertEqual(manifest["files"]["cover-letter.pdf"]["role"], "cover letter")
        self.put("cover-letter.typ", "Dear Editor,\n")
        self.assertEqual(submission.check(self.root)[0]["status"], "stale")
        self.put("cover-letter.typ", "Dear Editors,\n")
        self.put("submission/cover-letter.pdf", "edited by hand")
        self.assertEqual(submission.check(self.root)[0]["status"], "replaced")
        (self.root / "submission/cover-letter.pdf").unlink()
        self.assertEqual(submission.check(self.root)[0]["status"], "missing")
        # --note never fails; the strict check does.
        self.assertEqual(submission.main(["check", "--note", "--root", str(self.root)]), 0)
        self.assertEqual(submission.main(["check", "--root", str(self.root)]), 1)


def run_cases() -> bool:
    suite = unittest.defaultTestLoader.loadTestsFromTestCase(SubmissionCases)
    return unittest.TextTestRunner(verbosity=1).run(suite).wasSuccessful()


if __name__ == "__main__":
    raise SystemExit(0 if run_cases() else 1)
