"""The journal upload set: split outputs, the standalone graphic, the letter.

What this guards: the Word projection splits at exactly one SI heading or
refuses; the graphical abstract is written in the profile's format, flattened,
and measures inside the journal's box or fails on the resolution floor; a
profile names only a format this can write; the submission placement defaults
to the journal layout; a missing <si-start> probe is a clear error, not a
wrong page range; an absent cover-letter.typ is tolerated and leaves no stale
letter behind; and a recorded output reads stale when its source moves.
"""
from __future__ import annotations

import json
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import journal
from journal_cases import PROFILE
from PIL import Image

import submission

HEADING = "#heading(level: 1, numbering: none, outlined: false)[Supporting Information]"
WORD = f"""// GENERATED by tools/resolve_typst.py -- do not edit.
// second header line

= Title

Main text.

#bibliography("references.bib")

{HEADING}

SI text.
"""


class SubmissionCases(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        (self.root / ".build-state").mkdir()

    def tearDown(self):
        self.tmp.cleanup()

    def put(self, name: str, text: str) -> Path:
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        return path

    # --- Word split ----------------------------------------------------------

    def test_word_projection_splits_once_at_the_si_heading(self):
        main, si = submission.split_word_source(WORD)
        self.assertIn("Main text.", main)
        self.assertIn("#bibliography", main)
        self.assertNotIn("SI text.", main)
        self.assertNotIn("Supporting Information]", main)
        self.assertTrue(si.startswith("// GENERATED"))
        self.assertIn(HEADING, si)
        self.assertNotIn("Main text.", si)

    def test_word_split_refuses_zero_or_two_si_headings(self):
        for text in (WORD.replace(HEADING, ""), WORD + "\n" + HEADING + "\n"):
            with self.assertRaisesRegex(submission.SubmissionError, "one Supporting"):
                submission.split_word_source(text)

    # --- graphical abstract --------------------------------------------------

    def test_graphic_is_flattened_and_fits_the_box(self):
        src = self.root / "toc.png"
        Image.new("RGBA", (975, 525), (0, 0, 0, 0)).save(src, dpi=(72, 72))
        spec = {"width-in": 3.25, "height-in": 1.75, "min-dpi": 300}
        info = submission.export_graphic(src, self.root / "toc-graphic.tif", spec)
        self.assertEqual(info, {"format": "tif", "dpi": 300, "pixels": [975, 525]})
        out = Image.open(self.root / "toc-graphic.tif")
        self.assertEqual(out.mode, "RGB")
        self.assertEqual(out.getpixel((0, 0)), (255, 255, 255))
        self.assertAlmostEqual(out.info["dpi"][0], 300, places=0)
        # A wider source sets the resolution from its binding dimension.
        Image.new("RGB", (1950, 700)).save(src)
        info = submission.export_graphic(src, self.root / "toc-graphic.png", spec)
        self.assertEqual((info["format"], info["dpi"]), ("png", 600))

    def test_graphic_below_the_floor_fails(self):
        src = self.root / "small.png"
        Image.new("RGB", (300, 160)).save(src)
        spec = {"width-in": 3.25, "height-in": 1.75, "min-dpi": 300}
        with self.assertRaisesRegex(submission.SubmissionError, "floor is 300 dpi"):
            submission.export_graphic(src, self.root / "toc-graphic.tif", spec)

    def test_profile_file_format_is_validated(self):
        self.put("journals/ok.toml", PROFILE + 'file-format = "tif"\n')
        self.assertEqual(journal.load_profile(self.root, "ok").graphic["file-format"], "tif")
        self.put("journals/bad.toml", PROFILE + 'file-format = "eps"\n')
        with self.assertRaisesRegex(journal.JournalError, "file-format"):
            journal.load_profile(self.root, "bad")

    def test_submission_placement_defaults_to_the_journal_layout(self):
        self.put("journal.toml", 'schema_version = 1\nprofile = ""\n')
        self.assertEqual(journal.placement(self.root, "submission"), "journal")
        self.put("journal.toml", 'schema_version = 1\nprofile = ""\n'
                                 '[placement]\nsubmission = "none"\n')
        self.assertEqual(journal.placement(self.root, "submission"), "none")

    # --- split PDFs ------------------------------------------------------------

    @unittest.skipUnless(shutil.which("typst"), "typst not installed")
    def test_missing_si_probe_is_a_clear_error(self):
        self.put("paper.typ", "Main.\n#pagebreak()\nSI.\n")
        with self.assertRaisesRegex(submission.SubmissionError, "no <si-start> probe"):
            submission.si_start(self.root, "journal")
        self.put("paper.typ", "Main.\n#pagebreak()\n"
                              "#context [#metadata(here().page()) <si-start>]\nSI.\n")
        self.assertEqual(submission.si_start(self.root, "journal"), 2)

    def test_split_refuses_without_a_captured_manuscript(self):
        with self.assertRaisesRegex(submission.SubmissionError, "just paper"):
            submission.capture(self.root)

    # --- cover letter and records ----------------------------------------------

    def test_absent_cover_letter_is_tolerated_and_clears_a_stale_one(self):
        self.put("submission/cover-letter.pdf", "old")
        submission.save_records(self.root, {"cover-letter.pdf": {
            "kind": "files", "sources": {}, "output_hash": "x"}})
        note = submission.cover_letter(self.root)
        self.assertIn("no cover-letter.typ", note)
        self.assertFalse((self.root / "submission/cover-letter.pdf").exists())
        self.assertEqual(submission.load_records(self.root), {})

    def test_recorded_output_goes_stale_and_replaced(self):
        # The record hashes the running tool; point the tool path at this root.
        self.put("tools/submission.py", "# tool\n")
        self.put("cover-letter.typ", "Dear Editors,\n")
        staged = self.put("staged.pdf", "pdf")
        sources = submission.file_sources(self.root, ["cover-letter.typ"])
        sources["tools/submission.py"] = submission.digest(self.root / "tools/submission.py")
        submission.publish(self.root, staged, "cover-letter.pdf",
                           {"kind": "files", "sources": sources})
        rows = submission.check(self.root)
        self.assertEqual(rows, [{"output": "submission/cover-letter.pdf", "status": "current"}])
        manifest = json.loads((self.root / "submission/manifest.json").read_text())
        self.assertEqual(manifest["files"]["cover-letter.pdf"]["role"], "cover letter")
        self.put("cover-letter.typ", "Dear Editor,\n")
        self.assertEqual(submission.check(self.root)[0]["status"], "stale")
        self.put("cover-letter.typ", "Dear Editors,\n")
        self.put("submission/cover-letter.pdf", "edited by hand")
        self.assertEqual(submission.check(self.root)[0]["status"], "replaced")
        (self.root / "submission/cover-letter.pdf").unlink()
        self.assertEqual(submission.check(self.root)[0]["status"], "missing")
        # --note never fails; the strict check does.
        self.assertEqual(submission.main(["check", "--note", "--root", str(self.root)]), 0)
        self.assertEqual(submission.main(["check", "--root", str(self.root)]), 1)


def run_cases() -> bool:
    suite = unittest.defaultTestLoader.loadTestsFromTestCase(SubmissionCases)
    return unittest.TextTestRunner(verbosity=1).run(suite).wasSuccessful()


if __name__ == "__main__":
    raise SystemExit(0 if run_cases() else 1)
