// AUTO-GENERATED by scripts/gen_example_table.py -- do not edit by hand.
#table(
  columns: 5,
  align: (left, right, right, right, right),
  table.header(
    [Condition], [$n$], [Observed], [CI low], [CI high],
  ),
  [Control], [12], [1.02], [0.97], [1.08],
  [Treated], [12], [2.11], [2.01], [2.19],
  [Rescue], [11], [1.31], [1.22], [1.42],
)
