#!/usr/bin/env python3
"""Render stats.json into the file Typst reads.

WHY THIS STEP EXISTS. Typst has no format-spec: no thousands separator, no
`+.2f`, no fixed decimals. Its `str()` also rounds floats where Python's does not
(`1.0899999999999999` is `1.09` there and the full expansion here), so the two
disagree about exactly the values a paper cares about.

The old answer was to store the rendered string in stats.json beside the value.
That is a derived field living in a source file: redundant, driftable, and it
needed its own check to catch an edit to one that no longer matched the other.

So the formatting moved into the build instead. stats.json holds the VALUE and
the FORMAT; this renders them with Python's formatter -- the only formatter in
the pipeline -- into stats-rendered.json, which is what stats.typ reads. Nothing
is stored twice, so nothing can drift, and there is no check needed for a
disagreement that can no longer happen.

stats-rendered.json is a build artifact and is gitignored. Every recipe that
compiles the manuscript regenerates it first, so it cannot be stale.

Run with `just render-stats`; the compile recipes depend on it.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from paths import ROOT  # the manuscript (tools/paths.py)
sys.path.insert(0, str(Path(__file__).resolve().parent))

import typst_prose  # noqa: E402
from manifest_validation import load, ManifestError, guard_errors
from atomic_io import write_text

SRC = ROOT / "stats.json"
OUT = ROOT / "stats-rendered.json"

ABOUT = ("GENERATED by tools/render_stats.py from stats.json -- do not edit, and "
         "do not commit. Edit stats.json, or the generator that writes it.")


def render(SRC: Path, OUT: Path) -> int:
    if not SRC.is_file():
        # Not an error: the generated-numbers mechanism is optional, and a
        # manuscript that deleted it must still build. stats.typ is deleted along
        # with stats.json in that case, so nothing will read the output either.
        #
        # The derived file is removed rather than left behind: a stale
        # stats-rendered.json outliving its source is a corpse a compile could
        # still read, which is the one way this step could serve stale numbers.
        if OUT.is_file():
            OUT.unlink()
            print(f"no stats.json: removed the stale {OUT.name}")
        else:
            print("no stats.json: nothing to render")
        return 0

    try:
        doc = load(SRC, "stats")
    except ManifestError as e:
        print(str(e), file=sys.stderr)
        return 1
    values = doc.get("values")
    if not isinstance(values, dict):
        print("stats.json has no `values` table; run: just assets", file=sys.stderr)
        return 1

    out = {}
    for id, rec in sorted(values.items()):
        try:
            errors = guard_errors(rec["value"], {})
            if errors:
                raise ValueError("; ".join(errors))
            shown = typst_prose.display_of(rec)
        except (TypeError, ValueError) as e:
            print(f"{id}: cannot format {rec.get('value')!r} with "
                  f"{rec.get('fmt', '')!r}: {e}", file=sys.stderr)
            return 1
        # Only what Typst needs: `s` reads display, `n` reads value. The unit,
        # guards, provenance and description are for the audit and for
        # check_stats.py, and stay out of the compile's way. `unit` stays in
        # stats.json as metadata about the value -- unlike the deleted `source`
        # it describes the number rather than duplicating its provenance -- but
        # nothing in the document reads it, so it is not rendered.
        out[id] = {"display": shown, "value": rec.get("value")}

    # `#ci("id")` reads this table: an entry's own lo/hi, or a sibling pair
    # (id.lo/id.hi, id_lo/id_hi). Written only when there is one, so a paper
    # without intervals renders the same file as before.
    try:
        intervals = {id: {"display": r["display"], "with_level": r["with_level"]}
                     for id, r in sorted(typst_prose.intervals_of(values).items())}
    except (TypeError, ValueError) as e:
        print(f"cannot format an interval: {e}", file=sys.stderr)
        return 1
    write_text(OUT, json.dumps({"_about": ABOUT, "values": out,
                                **({"intervals": intervals} if intervals else {})},
                               indent=2) + "\n")
    print(f"rendered {len(out)} value(s) -> {OUT.name}")
    return 0


def main() -> int:
    return render(SRC, OUT)


if __name__ == "__main__":
    raise SystemExit(main())
