#!/usr/bin/env python3
"""Resolve the manuscript into plain Typst that another tool can read.

WHY THIS EXISTS. `paper.typ` is not self-contained Typst: it imports a
template, calls `#s()`, `#lit()`, `fig()` and `tbl()`, and pulls its identity
out of `config.typ`. Typst itself evaluates all of that. Nothing else does --
and "nothing else" now matters, because pandoc can read Typst and turn it into
a Word file with NATIVE equations or into LaTeX for a journal that demands it.
Pandoc's reader is a real evaluator, so it does not choke on the syntax; it
chokes on our helpers, which are ours to resolve.

So this writes `paper.resolved.typ`: the same manuscript with every helper
replaced by what it produces. One resolution step, feeding every export path.
The alternative -- teaching each exporter about `#s()` -- is how the word
count, the readability report and the narrator each grew their own copy of the
same logic, and how the same construct got fixed three separate times.

IT IS A BUILD ARTIFACT, exactly like stats-rendered.json: gitignored,
rewritten by every recipe that needs it, never edited by hand, and deleted
when its source is gone. Read it when a conversion looks wrong -- it is
precisely what the converter was fed.

WHAT IT RESOLVES, and why each one has to go:

    #s("id") / #n("id")   the value. Left alone, pandoc reports `Identifier
                          "s" not found` and stops.
    #lit("2.2")           the literal, as typed.
    #todo("...")          REFUSED, not stripped. `just paper` panics on an
                          unresolved note; an export is a real deliverable
                          too, so it gets the same answer rather than a
                          quietly cleaner file.
    fig("id", width: 70%) image("figures/x.png", width: 70%), from assets.json
    tbl("id")             the generated table's source, inlined
    #refn(<x>)            ref(<x>, supplement: none) -- the helper's own
                          definition, written out because its `#let` is
                          stripped along with the other directive lines
    @fig:x  @sec:x        #ref(<fig:x>). THIS ONE IS NOT COSMETIC: pandoc
                          reads `@fig` as a CITATION KEY and leaves `:x` as
                          stray text, so a cross-reference silently becomes
                          the words "[fig]:x" in the output. Only float and
                          section prefixes are rewritten; every other @key is
                          a real citation and must stay one.
    #ref(<fig:x>)         the literal text "Figure 3" / "Table S2", numbered
                          exactly as the PDF numbers it. Pandoc renders a
                          Typst ref as an EMPTY link, so every
                          cross-reference silently vanished from the Word
                          file; there is no target document to link into, and
                          what the PDF shows at that spot is plain text.
    #bibliography(...)    carried through from paper.typ's back matter, with
                          the `style:` identifier resolved to its literal
                          from config.typ. Left behind with the rest of the
                          back matter, every citation in the export dangled.
                          Placed in the PDF's position -- after the back
                          matter, BEFORE the SI -- not appended at the end,
                          where the reference list landed under the SI.

The count that numbers cross-references is also written into the definitions:
"Figure 3: " onto each caption, "2.1." onto each heading. Pandoc numbers
nothing, so the Word file showed prose saying "Figure 3" above captions that
carried no number at all.

Front matter is queried out of `config.typ` with `typst query` -- real Typst
evaluating the real file -- rather than parsed with a regex here. The template
itself is dropped: a converter cannot use Typst layout primitives, and a
journal supplies its own class file anyway. What the template SHOWS is not:
the back matter between BODY END and the bibliography (data availability,
authors, acknowledgment), the keywords and TOC graphic, and the SI's title
block all travel, rebuilt as plain content -- see _back_matter, _toc_block
and _si_title.

Usage:  just resolve            # -> paper.resolved.typ
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# The manuscript root, one level up: this file lives in tools/.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import readability  # noqa: E402
import typst_prose  # noqa: E402

OUT = ROOT / "paper.resolved.typ"
ASSETS = ROOT / "assets.json"

ABOUT = ("// GENERATED by tools/resolve_typst.py -- do not edit, do not commit.\n"
         "// The manuscript with every helper resolved, for pandoc. Edit\n"
         "// paper.typ / si-body.typ, or the analysis behind the numbers.\n")

# Label prefixes that are CROSS-REFERENCES rather than citation keys. `tab` is
# here because it is a common project convention (koth labels every table that
# way) and a manuscript using it would otherwise have every table reference
# silently turn into prose.
FLOAT_PREFIX = ("fig", "tbl", "tab", "eq", "sec")

# What a reference to each prefix reads as, and which counter it ticks. `tbl`
# and `tab` share one counter deliberately: both are figure(kind: table) by
# the conventions this scaffold documents, and Typst numbers by KIND, not by
# label spelling. The prefix->kind mapping is a convention, not something the
# label can prove; a manuscript that labels an image `tbl:` would be
# misnumbered here exactly as its readers would be misled by the label.
SUPPLEMENT = {"fig": "Figure", "tbl": "Table", "tab": "Table",
              "eq": "Equation", "sec": "Section"}
COUNTER = {"fig": "fig", "tbl": "tbl", "tab": "tbl", "eq": "eq"}

# Marks where the SI begins in the assembled text, so the crossref pass can
# reset its counters and switch to "S" numbering -- the same reset paper.typ's
# back matter performs with #counter(...).update(0) and an "S" numbering
# function. Same alphabet as the raw-span tokens, distinct pattern.
_SI_MARK = "\x00SI\x00"


class ResolveError(Exception):
    """The manuscript cannot be resolved into plain Typst."""


def _strip_comments(src: str) -> str:
    """Drop whole-line Typst comments.

    Whole-line only -- the same pattern readability.clean uses -- because a
    bare `//` inside a URL is not a comment. Applied to the manuscript AND to
    every generated table inlined into it: those carry an "AUTO-GENERATED"
    header, and inlining one into a `#figure(...)` argument put a comment
    inside a call, which pandoc's reader rejects outright.
    """
    return re.sub(r"(?m)^\s*//.*$", "", src)


_RAW_BACK = re.compile("\x00R(\\d+)\x00")


def _protect_raw(src: str) -> tuple[str, list[str]]:
    """Set aside raw spans -- ``` fences and `inline code` -- as opaque tokens.

    Typst treats raw content as inert, so a documentation example like
    `#s("id")` inside backticks is VERBATIM in the PDF -- and must stay
    verbatim in the export. Without this, the notation passes below either
    rejected such an example (undeclared id) or silently replaced it with the
    number. readability.clean has the same problem and strips raw spans
    entirely; here they are deliverable content, so they are stashed before
    any pass runs and restored, untouched, at the end.

    Fences first, so a backtick inside one is not paired as inline code.
    Inline spans are single-line on purpose: a lone backtick in prose must not
    pair across lines with one in a comment, or the comment's text would ride
    back in through the restore. A token stashed FROM a comment line dies with
    the line in _strip_comments, which is the order that makes both safe.
    """
    spans: list[str] = []

    def stash(m: re.Match) -> str:
        spans.append(m.group(0))
        return f"\x00R{len(spans) - 1}\x00"

    src = re.sub(r"```.*?```", stash, src, flags=re.S)
    src = re.sub(r"`[^`\n]*`", stash, src)
    return src, spans


def _restore_raw(src: str, spans: list[str]) -> str:
    """Put the stashed raw spans back where their tokens stand."""
    return _RAW_BACK.sub(lambda m: spans[int(m.group(1))], src)


def _query_front_matter() -> dict:
    """Title, authors and affiliations, evaluated by Typst itself.

    A regex over config.typ would be the obvious shortcut and the wrong one:
    the author line is BUILT there (initials, suffixes, particles -- see
    surname-of), so only Typst knows what it comes to. This asks Typst.
    """
    probe = ('#import "/config.typ": paper-title, paper-authors, '
             'paper-affiliations, paper-date, paper-keywords\n'
             "#metadata((title: paper-title, "
             "authors: paper-authors.map(a => a.name), "
             "affils: paper-affiliations, date: paper-date, "
             "keywords: paper-keywords)) <rmeta>\n")
    with tempfile.NamedTemporaryFile("w", suffix=".typ", dir=ROOT,
                                     delete=False) as fh:
        fh.write(probe)
        tmp = Path(fh.name)
    try:
        proc = subprocess.run(
            ["typst", "query", "--root", str(ROOT), str(tmp), "<rmeta>",
             "--field", "value", "--one"],
            capture_output=True, text=True, cwd=ROOT)
        if proc.returncode != 0:
            raise ResolveError(
                f"could not read the front matter out of config.typ: "
                f"{proc.stderr.strip().splitlines()[-1] if proc.stderr.strip() else '?'}")
        return json.loads(proc.stdout)
    finally:
        tmp.unlink(missing_ok=True)


def _abstract() -> str:
    """The abstract's SOURCE, from `#let paper-abstract = [...]`.

    Content, not a string, so it cannot come back through `typst query` as
    metadata. Taken as source text and handed on unresolved -- it is prose,
    and the notation pass below resolves whatever it contains.

    Fails LOUD, like _query_front_matter beside it. Returning "" on a
    manuscript whose abstract is a string, built from variables, or renamed
    ships an export with an empty Abstract section at exit 0 -- on the one
    output nobody re-reads before sending. Comments are stripped before the
    bracket count for the same reason: a `]` inside a `//` comment closed the
    count early and truncated the abstract mid-sentence, silently.
    """
    raw = _strip_comments((ROOT / "config.typ").read_text())
    m = re.search(r"#let\s+paper-abstract\s*=\s*\[", raw)
    if not m:
        raise ResolveError(
            "config.typ has no `#let paper-abstract = [...]` this resolver "
            "can read. If the abstract is a string or built from variables, "
            "rewrite it as a plain content block -- otherwise the export "
            "would ship with an empty Abstract section and no error.")
    depth, start = 0, m.end() - 1
    for i in range(start, len(raw)):
        if raw[i] == "[":
            depth += 1
        elif raw[i] == "]":
            depth -= 1
            if depth == 0:
                return raw[start + 1:i].strip()
    raise ResolveError(
        "config.typ: the paper-abstract content block never closes -- "
        "unbalanced brackets in the abstract.")


def resolve_notation(src: str, assets: dict, where: str) -> str:
    """Replace every project helper with what Typst would render for it."""
    # Raw spans go FIRST: a `#s()` or `#todo()` inside backticks is verbatim
    # content in the PDF, not a call, and no pass below may touch it.
    src, raw_spans = _protect_raw(src)

    # Comments next, and BEFORE the #todo refusal. si-body.typ documents its
    # own usage with a literal `#s("id")` in a comment block, and resolving
    # that asked stats.json for a value named "id"; a `#todo` mentioned in a
    # comment is the same case -- Typst never evaluates it, `just paper`
    # builds clean, and refusing the export over it was a false alarm.
    src = _strip_comments(src)

    # A note that cannot ship must not ship through a side door either.
    todo = re.search(typst_prose.TODO, src)
    if todo:
        raise ResolveError(
            f'unresolved #todo("{todo.group(1)}") in {where}. An export is a '
            f"deliverable: resolve the note and delete the call, exactly as "
            f"`just paper` requires.")

    # Standalone directive lines -- the same pattern readability.clean uses.
    # si-body.typ carries `#import "stats.typ"`, `#import "assets.typ"` and
    # `#let refn(...)`; left in place they make the "self-contained" output
    # depend on the project helpers and on gitignored stats-rendered.json, so
    # pandoc run from any other directory fails inside the very files this
    # resolver exists to eliminate. Every call they served is resolved below.
    src = re.sub(r"(?m)^\s*#(?:import|let|set|show)\b.*$", "", src)

    src = typst_prose.resolve_stats(src)
    src = typst_prose.resolve_lit(src)

    def asset(m: re.Match) -> str:
        hash, kind, id, args = (m.group(1), m.group(2), m.group(3),
                                m.group(4) or "")
        if id not in assets:
            raise ResolveError(
                f"{where} references {kind}(\"{id}\"), which assets.json does "
                f"not declare -- run: just assets")
        path = assets[id]["path"]
        # The matched `#` is re-emitted: it is what distinguishes a markup-mode
        # call from a code-mode one, and dropping it turned `#fig("id")` in
        # running prose into the literal words image("...") in the deliverable.
        if kind == "fig":
            return f'{hash}image("{path}"{args})'
        # A table is inlined rather than left as `include`: the generated file
        # is small, it is ours, and one fewer path for the converter to
        # resolve is one fewer way for the export to lose a table silently.
        target = ROOT / path
        if not target.is_file():
            raise ResolveError(f"{where}: {path} is missing -- run: just assets")
        # Wrapped in content brackets, and that is semantic rather than
        # cosmetic. `tbl()` resolves to `include`, and an include brings in
        # MARKUP -- where a generated table's leading `#table(` is correct.
        # Pasting that text straight into `#figure(...)`'s argument list drops
        # it into CODE mode, where a leading `#` is a syntax error. The
        # brackets put it back in markup, which is what include meant. In
        # markup mode (`#tbl(...)`), the re-emitted hash makes it `#[...]`,
        # the content block markup requires.
        return hash + "[\n" + _strip_comments(target.read_text()).strip() + "\n]"

    src = typst_prose.ASSET_CALL.sub(asset, src)

    # The project's own bare-number reference helper. Its `#let` was stripped
    # above, so the definition -- `ref(l, supplement: none)` -- is written out
    # here; plain `#ref(\1)` shipped exports reading "Table Table S1". The
    # matched hash is carried through, so a code-mode `refn(...)` does not
    # gain an invalid `#`.
    #
    # The `,?` is load-bearing and was missing from the first draft, which
    # then died on a real manuscript at `#refn(\n  <tbl:x>,\n)`. typstyle
    # breaks a long line INSIDE the call and leaves a trailing comma; every
    # shared pattern in typst_prose.py ends `,?\s*\)` for exactly this reason,
    # and this is the fourth time this repository has been bitten by it.
    src = re.sub(r"(?<![A-Za-z0-9_-])(#?)refn\(\s*(<[^>]+>)\s*,?\s*\)",
                 r"\1ref(\2, supplement: none)", src)

    # @fig:x -> #ref(<fig:x>). See the module docstring: pandoc reads the @ as
    # citation syntax, so leaving these alone turns every cross-reference into
    # stray prose. Citations (@lovelace1843) are deliberately untouched. The
    # label part repeats typst_prose.CITE's segment class because labels may
    # be multi-segment (@fig:panel:a); capturing one segment truncated them.
    src = re.sub(rf"@({'|'.join(FLOAT_PREFIX)}):"
                 rf"([A-Za-z0-9_-]+(?::[A-Za-z0-9_-]+)*)",
                 r"#ref(<\1:\2>)", src)
    return _restore_raw(src, raw_spans)


# A float's label, standing on its own after the #figure(...) call -- as
# opposed to inside a ref, where `<` directly follows `(`. Multi-segment, as
# everywhere else.
_DEF = re.compile(rf"(?<!\()<({'|'.join(FLOAT_PREFIX)}):"
                  rf"[A-Za-z0-9_-]+(?::[A-Za-z0-9_-]+)*>")
_HEADING = re.compile(r"(?m)^(=+)\s+\S[^\n]*$")
_REF = re.compile(r"(#?)ref\(\s*(<[^>]+>)\s*"
                  r"(,\s*supplement:\s*none\s*)?,?\s*\)")
_FIGURE_OPEN = re.compile(r"#?figure\(")
_CAPTION = re.compile(r"caption:\s*\[")


def resolve_crossrefs(head: str, body: str) -> str:
    """Every ref call becomes the literal text the PDF shows for it.

    Pandoc renders a Typst ref as an EMPTY link -- there is no page number to
    print and no target document to link into -- so every cross-reference
    silently vanished from the Word file: "see and here". What the PDF shows
    at that spot is text, and the numbering behind it is deterministic: floats
    count per kind in document order, headings nest, and the SI resets both
    with an "S" prefix (the #counter(...).update(0) block in paper.typ's back
    matter). This reimplements that count and writes the text in.

    The same count is written into the DEFINITIONS, not just the references:
    "Figure 3: " ahead of each caption, "2.1." (SI: "S2.1") ahead of each
    heading. Typst supplies those numbers at layout time and pandoc supplies
    nothing, so the Word file showed unnumbered captions under prose saying
    "Figure 3" -- every cross-reference pointed at a number no caption
    carried. Heading numbers follow the PDF's styles: arkheion's "1."
    pattern (trailing dot) for the main text, the back matter's "S1"
    function (no trailing dot) for the SI.

    `head` (title, authors, abstract) and `body` arrive separately because
    only the body is scanned for numbering -- the manuscript does not number
    the title or Abstract headings -- while references are REPLACED in both,
    since the abstract may point into the body. A ref to a label that no
    float or heading in the export defines is an error, not a link left to
    vanish: the target lives in the dropped back matter or nowhere, and
    either way the reader would get prose pointing at nothing.
    """
    head, head_spans = _protect_raw(head)
    body, body_spans = _protect_raw(body)

    numbered: dict[str, str] = {}
    counters = {"fig": 0, "tbl": 0, "eq": 0}
    levels: list[int] = []
    si = False
    # (position, text) pairs written into `body` after the scan -- inserting
    # during it would shift every position the events were sorted on.
    inserts: list[tuple[int, str]] = []

    def number(n: int) -> str:
        return f"S{n}" if si else str(n)

    # Every #figure(...) call's span, so a def label can find the caption it
    # belongs to. Computed on the raw-protected body: a `#figure(` quoted in
    # backticks is prose, not a float.
    fig_spans = []
    for fm in _FIGURE_OPEN.finditer(body):
        end = _paren_end(body, fm.end() - 1)
        if end is not None:
            fig_spans.append((fm.start(), end))

    def caption_insert(label_at: int, prefix: str, num: str) -> None:
        """Queue "Figure 3: " onto the caption of the float labeled here.

        The label follows its #figure(...) call across whitespace only; a
        float without a caption (or an equation, which has none) is left
        alone -- the PDF shows no caption text to number there either.
        """
        span = next((s for s in fig_spans if s[1] <= label_at
                     and not body[s[1]:label_at].strip()), None)
        if span is None:
            return
        cap = _CAPTION.search(body, span[0], span[1])
        if cap:
            inserts.append((cap.end(), f"{SUPPLEMENT[prefix]} {num}: "))

    events = (
        [(m.start(), "def", m) for m in _DEF.finditer(body)]
        + [(m.start(), "head", m) for m in _HEADING.finditer(body)])
    if _SI_MARK in body:
        events.append((body.index(_SI_MARK), "si", None))
    for _, what, m in sorted(events, key=lambda e: e[0]):
        if what == "si":
            counters = {"fig": 0, "tbl": 0, "eq": 0}
            levels, si = [], True
        elif what == "head":
            depth = len(m.group(1))
            levels = levels[:depth] + [0] * (depth - len(levels))
            levels[depth - 1] += 1
            joined = ".".join(str(n) for n in levels)
            inserts.append((m.end(1),
                            f" S{joined}" if si else f" {joined}."))
        else:
            prefix = m.group(1)
            # A sec label names the heading it follows -- usually on the same
            # line, on its own line when typstyle wraps a long title. Either
            # way its def event sorts after the heading's bump, so "the
            # current number" is its number.
            if prefix == "sec":
                if levels:
                    numbered[m.group(0)] = \
                        ("S" if si else "") + ".".join(str(n) for n in levels)
                continue
            counters[COUNTER[prefix]] += 1
            numbered[m.group(0)] = number(counters[COUNTER[prefix]])
            if prefix != "eq":
                caption_insert(m.start(), prefix,
                               numbered[m.group(0)])

    for at, text in sorted(inserts, reverse=True):
        body = body[:at] + text + body[at:]

    def ref(m: re.Match) -> str:
        hash, label, bare = m.group(1), m.group(2), bool(m.group(3))
        if label not in numbered:
            raise ResolveError(
                f"reference to {label}, but no float or heading in the "
                f"export carries that label -- it lives in the dropped back "
                f"matter, or nowhere. The reader would get prose pointing at "
                f"nothing.")
        prefix = label[1:].split(":", 1)[0]
        text = numbered[label] if bare else \
            f"{SUPPLEMENT[prefix]} {numbered[label]}"
        # Markup-mode `#ref(...)` becomes plain prose; a code-mode call sits
        # in an argument list, where bare words are an error and a content
        # block `[...]` is the literal it meant.
        return text if hash else f"[{text}]"

    head = _restore_raw(_REF.sub(ref, head), head_spans)
    body = _restore_raw(_REF.sub(ref, body), body_spans)
    return (head + body).replace(_SI_MARK, "")


def _paren_end(src: str, at: int) -> int | None:
    """Index just past the `)` matching the `(` at `at`, or None."""
    depth = 0
    for i in range(at, len(src)):
        if src[i] == "(":
            depth += 1
        elif src[i] == ")":
            depth -= 1
            if depth == 0:
                return i + 1
    return None


def _call_span(src: str, opener: str) -> str | None:
    """The full text of `opener ... )` with balanced parentheses, or None."""
    at = src.find(opener)
    if at < 0:
        return None
    end = _paren_end(src, at + len(opener) - 1)
    return None if end is None else src[at:end]


def bibliography_line(paper_src: str, config_src: str) -> str:
    """The manuscript's #bibliography(...) call, made self-contained.

    It sits in paper.typ's back matter -- outside the BODY markers -- so the
    body slice drops it, and without it every citation in the export dangles:
    Typst cannot resolve the @keys and citeproc has no entries to set. The
    call is carried through verbatim except for one substitution: `style:`
    usually names a config.typ variable (`paper-bib-style`), whose `#let` does
    not travel, so the identifier is resolved to its string literal here.

    Returns "" for a manuscript with no bibliography, which is legal.
    """
    call = _call_span(_strip_comments(paper_src), "#bibliography(")
    if call is None:
        return ""
    m = re.search(r"style:\s*([A-Za-z_][A-Za-z0-9_-]*)\b", call)
    if m and m.group(1) != "none":
        let = re.search(
            rf'#let\s+{re.escape(m.group(1))}\s*=\s*"([^"]+)"',
            _strip_comments(config_src))
        if not let:
            raise ResolveError(
                f"#bibliography(style: {m.group(1)}): no "
                f'`#let {m.group(1)} = "..."` in config.typ to resolve it '
                f"from. Name a string literal, or define the variable there.")
        call = call.replace(m.group(0), f'style: "{let.group(1)}"')
    return call


def _back_matter(paper_src: str, assets: dict) -> str:
    """The prose between BODY END and the bibliography, resolved.

    Associated Content, Author Information, Acknowledgment: it is back matter
    by the word-count's definition, but it is CONTENT -- a journal reads the
    data-availability statement and the author list from the Word file -- and
    dropping it with the template shipped exports missing all three sections.
    The slice ends at the #bibliography call; failing that, at the first
    piece of SI-appendix machinery (page break, si-body include), which is
    layout and counter surgery no converter can use.
    """
    m = readability.BODY_END.search(paper_src)
    if not m:
        return ""
    tail = paper_src[m.end():]
    cut = len(tail)
    for anchor in ("#bibliography(", "#pagebreak()",
                   '#include "si-body.typ"'):
        at = tail.find(anchor)
        if 0 <= at < cut:
            cut = at
    return resolve_notation(tail[:cut], assets,
                            "paper.typ (back matter)").strip()


def _si_title(meta: dict) -> str:
    """The SI's title block: what the PDF centers ahead of the appendix.

    paper.typ builds it from align/text primitives inside a docx-mode
    conditional, neither of which travels (the conditional's `docx-mode` is a
    stripped #let), so it is synthesized here from the same front matter.
    A #heading CALL rather than `= ` markup, for the same reason the PDF
    passes `numbering: none`: the crossref pass numbers markup headings, and
    this one must not tick Section S1 away from the SI's first real section.
    """
    authors = ", ".join(meta.get("authors", []))
    return ("#heading(level: 1, numbering: none, outlined: false)"
            "[Supporting Information]\n\n"
            f"{meta.get('title', '')}\n\n"
            + (f"_{authors}_\n\n" if authors else ""))


def _toc_block(paper_src: str, assets: dict) -> str:
    """The abstract/TOC graphic and its caption, when the front matter has one.

    The convention is paper.typ's own: `#let toc-graphic = ...` (usually a
    fig() call) with an optional `#let toc-caption = [...]` beside it. Both
    sit in layout wrappers the export cannot use, so the bindings are read
    directly and emitted as plain content -- image, then italic caption --
    exactly as paper.typ's docx-mode branch lays them out. A manuscript
    without the binding gets "" and no TOC graphic, which is legal.
    """
    m = readability.BODY_START.search(paper_src)
    front = _strip_comments(paper_src[:m.start()] if m else paper_src)
    g = re.search(r"(?m)^#let\s+toc-graphic\s*=\s*(\S.*)$", front)
    if not g:
        return ""
    expr = g.group(1).strip()
    block = resolve_notation(expr if expr.startswith("#") else "#" + expr,
                             assets, "paper.typ (toc-graphic)").strip()
    c = re.search(r"#let\s+toc-caption\s*=\s*\[", front)
    if c:
        # The same bracket walk as the abstract: a regex to `]` truncates the
        # caption at the first nested bracket.
        depth = 0
        for i in range(c.end() - 1, len(front)):
            if front[i] == "[":
                depth += 1
            elif front[i] == "]":
                depth -= 1
                if depth == 0:
                    cap = resolve_notation(front[c.end():i].strip(), assets,
                                           "paper.typ (toc-caption)")
                    block += f"\n\n_{cap}_"
                    break
    return block


def build() -> str:
    if not ASSETS.is_file():
        assets = {}
    else:
        assets = json.loads(ASSETS.read_text()).get("values", {})

    meta = _query_front_matter()
    paper_src = (ROOT / "paper.typ").read_text()
    body = readability.slice_body(paper_src)
    body = resolve_notation(body, assets, "paper.typ")

    # Back matter and the bibliography, IN THE PDF'S ORDER: main text, then
    # Associated Content / Author Information / Acknowledgment, then the
    # references, then the SI. The bibliography used to be appended after
    # everything, which citeproc read literally -- the reference list landed
    # at the very bottom of the Word file, underneath the entire SI.
    back = _back_matter(paper_src, assets)
    if back:
        body += "\n\n" + back
    bib = bibliography_line(paper_src, (ROOT / "config.typ").read_text())
    if bib:
        body += "\n\n" + bib

    # The SI is read as its own file, exactly as readability.py and the
    # narrator read it. paper.typ DOES `#include "si-body.typ"`, but that line
    # sits outside the BODY markers -- back matter does, by this scaffold's
    # convention -- so slicing the body drops it. Following the include from
    # inside the body instead silently produced a manuscript with no SI and
    # therefore no tables, which is how this was found.
    #
    # UNLESS the include survived the slice: on a migrated manuscript the
    # markers are new and nothing enforces which side of them the include
    # landed on. Appending anyway would put the entire SI in twice -- once
    # here, once through the inliner below -- silently.
    si = ROOT / "si-body.typ"
    if si.is_file() and not re.search(r'#include\s+"/?si-body\.typ"', body):
        # The marker sits on its own line so the SI's first heading still
        # starts a line, which is what the heading scan anchors on.
        body += ("\n\n" + _SI_MARK + "\n" + _si_title(meta)
                 + resolve_notation(si.read_text(), assets, "si-body.typ"))

    # Any OTHER include inside the body is inlined where it stands. The SI,
    # when its include survived inside the markers, is marked here instead:
    # the crossref pass needs to know where the counters reset.
    def inline(m: re.Match) -> str:
        # Typst resolves a leading "/" against the project root, not the OS's.
        target = ROOT / m.group(1).lstrip("/")
        if not target.is_file():
            raise ResolveError(f"paper.typ includes {m.group(1)}, which is missing")
        mark = _SI_MARK + "\n" + _si_title(meta) if target == si else ""
        return mark + resolve_notation(target.read_text(), assets, m.group(1))

    body = re.sub(r'#include\s+"([^"]+)"', inline, body)

    authors = ", ".join(meta.get("authors", []))
    affils = "\n".join(f"{i + 1}. {a}" for i, a in
                       enumerate(meta.get("affils", [])))
    abstract = resolve_notation(_abstract(), assets, "config.typ (abstract)")
    keywords = ", ".join(meta.get("keywords") or [])
    toc = _toc_block(paper_src, assets)

    head = (
        f"{ABOUT}\n"
        f"= {meta.get('title', '')}\n\n"
        f"{authors}\n\n"
        f"{affils}\n\n"
        f"== Abstract\n\n{abstract}\n\n"
        + (f"*Keywords:* {keywords}\n\n" if keywords else "")
        + (toc + "\n\n" if toc else "")
    )
    return resolve_crossrefs(head, body) + "\n"


def main() -> int:
    try:
        OUT.write_text(build())
    except ResolveError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    n = len(OUT.read_text().splitlines())
    print(f"wrote {OUT.name} ({n:,} lines) -- plain Typst, for pandoc")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
