#!/usr/bin/env python3
"""Adapt a captured Typst manuscript for Pandoc and Word.

The shared intermediate is produced by manuscript_snapshot.py. It preserves
Typst's template, include scopes and reference identities for the PDF build.
This module subsequently removes layout machinery Pandoc cannot use, emits
plain front matter and tables, and writes actual compiled reference numbers
into the Word projection. Never use this projection as the PDF input.

The shared build supplies --root, --numbers and --output. The numbers come
from Typst evaluating that same captured manuscript, including unlabeled
floats and SI counter resets. The pure resolve_crossrefs helper retains its
legacy fallback for callers/tests; publishing always supplies native numbers.

paper.resolved.typ at the project root remains a generated compatibility
preview of paper.word.typ inside the latest snapshot. Edit the manuscript
sources, never either generated file. A direct invocation without --numbers
runs the shared build, just like `just resolve`.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# The manuscript root, one level up: this file lives in tools/.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

import readability  # noqa: E402
import typst_prose  # noqa: E402
from manuscript_sources import (
    call_span, mask, si_bibliography, without_si_bibliography)
from atomic_io import write_text

OUT = ROOT / "paper.resolved.typ"
ASSETS = ROOT / "assets.json"
NATIVE_NUMBERING = None

ABOUT = ("// GENERATED by tools/resolve_typst.py -- do not edit, do not commit.\n"
         "// The manuscript with every helper resolved, for pandoc. Edit\n"
         "// paper.typ / si-body.typ, or the analysis behind the numbers.\n")

# Label prefixes that are CROSS-REFERENCES rather than citation keys. `tab` is
# here because it is a common project convention (koth labels every table that
# way) and a manuscript using it would otherwise have every table reference
# silently turn into prose.
FLOAT_PREFIX = ("fig", "tbl", "tab", "eq", "sec")

# What a reference to each prefix reads as, and which counter it ticks. `tbl`
# and `tab` share one counter deliberately: both are figure(kind: table) by
# the conventions this scaffold documents, and Typst numbers by KIND, not by
# label spelling. The prefix->kind mapping is a convention, not something the
# label can prove; a manuscript that labels an image `tbl:` would be
# misnumbered here exactly as its readers would be misled by the label.
SUPPLEMENT = {"fig": "Figure", "tbl": "Table", "tab": "Table",
              "eq": "Equation", "sec": "Section"}
COUNTER = {"fig": "fig", "tbl": "tbl", "tab": "tbl", "eq": "eq"}

# Marks where the SI begins in the assembled text, so the crossref pass can
# reset its counters and switch to "S" numbering -- the same reset paper.typ's
# back matter performs with #counter(...).update(0) and an "S" numbering
# function. Same alphabet as the raw-span tokens, distinct pattern.
_SI_MARK = "\x00SI\x00"


class ResolveError(Exception):
    """The manuscript cannot be resolved into plain Typst."""


def _strip_comments(src: str) -> str:
    """Drop whole-line Typst comments.

    Whole-line only -- the same pattern readability.clean uses -- because a
    bare `//` inside a URL is not a comment. Applied to the manuscript AND to
    every generated table inlined into it: those carry an "AUTO-GENERATED"
    header, and inlining one into a `#figure(...)` argument put a comment
    inside a call, which pandoc's reader rejects outright.
    """
    return re.sub(r"(?m)^\s*//.*$", "", src)


_RAW_BACK = re.compile("\x00R(\\d+)\x00")


def _protect_raw(src: str) -> tuple[str, list[str]]:
    """Set aside raw spans -- ``` fences and `inline code` -- as opaque tokens.

    Typst treats raw content as inert, so a documentation example like
    `#s("id")` inside backticks is VERBATIM in the PDF -- and must stay
    verbatim in the export. Without this, the notation passes below either
    rejected such an example (undeclared id) or silently replaced it with the
    number. readability.clean has the same problem and strips raw spans
    entirely; here they are deliverable content, so they are stashed before
    any pass runs and restored, untouched, at the end.

    Fences first, so a backtick inside one is not paired as inline code.
    Inline spans are single-line on purpose: a lone backtick in prose must not
    pair across lines with one in a comment, or the comment's text would ride
    back in through the restore. A token stashed FROM a comment line dies with
    the line in _strip_comments, which is the order that makes both safe.
    """
    spans: list[str] = []

    def stash(m: re.Match) -> str:
        spans.append(m.group(0))
        return f"\x00R{len(spans) - 1}\x00"

    src = re.sub(r"```.*?```", stash, src, flags=re.S)
    src = re.sub(r"`[^`\n]*`", stash, src)
    return src, spans


def _restore_raw(src: str, spans: list[str]) -> str:
    """Put the stashed raw spans back where their tokens stand."""
    return _RAW_BACK.sub(lambda m: spans[int(m.group(1))], src)


def front_matter_probe(*, label: bool = True) -> str:
    """Typst metadata shared by the standalone and combined build queries."""
    # Each author comes back as (name, affils), where affils is the author's
    # affiliation NUMBERS -- positions in paper-affiliations, the same list
    # the head prints below the author line, so the superscripts cannot
    # disagree with it. Both config shapes are normalized here in Typst:
    # `affiliation: "..."` (one string) and `affiliations: (...)` (a tuple).
    return ('#import "/config.typ": paper-title, paper-authors, '
             'paper-affiliations, paper-date, paper-keywords\n'
             "#metadata((front_matter_schema: 1, title: paper-title, "
             "authors: paper-authors.map(a => (name: a.name, "
             'affils: a.at("affiliations", default: '
             '(a.at("affiliation", default: none),))'
             ".filter(x => x != none)"
             ".map(af => paper-affiliations.position(x => x == af))"
             ".filter(p => p != none).map(p => p + 1))), "
             "affils: paper-affiliations, date: paper-date, "
             "keywords: paper-keywords))" + (" <rmeta>" if label else "") + "\n")


def _query_front_matter() -> dict:
    """Title, authors and affiliations, evaluated by Typst itself.

    A regex over config.typ would be the obvious shortcut and the wrong one:
    the author line is BUILT there (initials, suffixes, particles -- see
    surname-of), so only Typst knows what it comes to. This asks Typst.
    """
    with tempfile.NamedTemporaryFile("w", suffix=".typ", dir=ROOT,
                                     delete=False) as fh:
        fh.write(front_matter_probe())
        tmp = Path(fh.name)
    try:
        proc = subprocess.run(
            ["typst", "query", "--root", str(ROOT), str(tmp), "<rmeta>",
             "--field", "value", "--one"],
            capture_output=True, text=True, cwd=ROOT)
        if proc.returncode != 0:
            raise ResolveError(
                f"could not read the front matter out of config.typ: "
                f"{proc.stderr.strip().splitlines()[-1] if proc.stderr.strip() else '?'}")
        return json.loads(proc.stdout)
    finally:
        tmp.unlink(missing_ok=True)


def _abstract() -> str:
    """The abstract's SOURCE, from `#let paper-abstract = [...]`.

    Content, not a string, so it cannot come back through `typst query` as
    metadata. Taken as source text and handed on unresolved -- it is prose,
    and the notation pass below resolves whatever it contains.

    Fails LOUD, like _query_front_matter beside it. Returning "" on a
    manuscript whose abstract is a string, built from variables, or renamed
    ships an export with an empty Abstract section at exit 0 -- on the one
    output nobody re-reads before sending. Comments are stripped before the
    bracket count for the same reason: a `]` inside a `//` comment closed the
    count early and truncated the abstract mid-sentence, silently.
    """
    raw = _strip_comments((ROOT / "config.typ").read_text())
    m = re.search(r"#let\s+paper-abstract\s*=\s*\[", raw)
    if not m:
        raise ResolveError(
            "config.typ has no `#let paper-abstract = [...]` this resolver "
            "can read. If the abstract is a string or built from variables, "
            "rewrite it as a plain content block -- otherwise the export "
            "would ship with an empty Abstract section and no error.")
    depth, start = 0, m.end() - 1
    for i in range(start, len(raw)):
        if raw[i] == "[":
            depth += 1
        elif raw[i] == "]":
            depth -= 1
            if depth == 0:
                return raw[start + 1:i].strip()
    raise ResolveError(
        "config.typ: the paper-abstract content block never closes -- "
        "unbalanced brackets in the abstract.")


def resolve_notation(src: str, assets: dict, where: str) -> str:
    """Replace every project helper with what Typst would render for it."""
    # Raw spans go FIRST: a `#s()` or `#todo()` inside backticks is verbatim
    # content in the PDF, not a call, and no pass below may touch it.
    src, raw_spans = _protect_raw(src)

    # Comments next, and BEFORE the #todo refusal. si-body.typ documents its
    # own usage with a literal `#s("id")` in a comment block, and resolving
    # that asked stats.json for a value named "id"; a `#todo` mentioned in a
    # comment is the same case -- Typst never evaluates it, `just paper`
    # builds clean, and refusing the export over it was a false alarm.
    src = _strip_comments(src)

    # A note that cannot ship must not ship through a side door either.
    todo = re.search(typst_prose.TODO, src)
    if todo:
        raise ResolveError(
            f'unresolved #todo("{todo.group(1)}") in {where}. An export is a '
            f"deliverable: resolve the note and delete the call, exactly as "
            f"`just paper` requires.")

    # Standalone directive lines -- the same pattern readability.clean uses.
    # si-body.typ carries `#import "stats.typ"`, `#import "assets.typ"` and
    # `#let refn(...)`; left in place they make the "self-contained" output
    # depend on the project helpers and on gitignored stats-rendered.json, so
    # pandoc run from any other directory fails inside the very files this
    # resolver exists to eliminate. Every call they served is resolved below.
    src = re.sub(r"(?m)^\s*#(?:import|let|set|show)\b.*$", "", src)

    src = typst_prose.resolve_stats(src)
    src = typst_prose.resolve_lit(src)

    def asset(m: re.Match) -> str:
        hash, kind, id, args = (m.group(1), m.group(2), m.group(3),
                                m.group(4) or "")
        if id not in assets:
            raise ResolveError(
                f"{where} references {kind}(\"{id}\"), which assets.json does "
                f"not declare -- run: just assets")
        path = assets[id]["path"]
        # The matched `#` is re-emitted: it is what distinguishes a markup-mode
        # call from a code-mode one, and dropping it turned `#fig("id")` in
        # running prose into the literal words image("...") in the deliverable.
        if kind == "fig":
            return f'{hash}image("{path}"{args})'
        # A table is inlined rather than left as `include`: the generated file
        # is small, it is ours, and one fewer path for the converter to
        # resolve is one fewer way for the export to lose a table silently.
        target = ROOT / path
        if not target.is_file():
            raise ResolveError(f"{where}: {path} is missing -- run: just assets")
        # Wrapped in content brackets, and that is semantic rather than
        # cosmetic. `tbl()` resolves to `include`, and an include brings in
        # MARKUP -- where a generated table's leading `#table(` is correct.
        # Pasting that text straight into `#figure(...)`'s argument list drops
        # it into CODE mode, where a leading `#` is a syntax error. The
        # brackets put it back in markup, which is what include meant. In
        # markup mode (`#tbl(...)`), the re-emitted hash makes it `#[...]`,
        # the content block markup requires.
        return hash + "[\n" + _strip_comments(target.read_text()).strip() + "\n]"

    src = typst_prose.ASSET_CALL.sub(asset, src)

    # The project's own bare-number reference helper. Its `#let` was stripped
    # above, so the definition -- `ref(l, supplement: none)` -- is written out
    # here; plain `#ref(\1)` shipped exports reading "Table Table S1". The
    # matched hash is carried through, so a code-mode `refn(...)` does not
    # gain an invalid `#`.
    #
    # The `,?` is load-bearing and was missing from the first draft, which
    # then died on a real manuscript at `#refn(\n  <tbl:x>,\n)`. typstyle
    # breaks a long line INSIDE the call and leaves a trailing comma; every
    # shared pattern in typst_prose.py ends `,?\s*\)` for exactly this reason,
    # and this is the fourth time this repository has been bitten by it.
    src = re.sub(r"(?<![A-Za-z0-9_-])(#?)refn\(\s*(<[^>]+>)\s*,?\s*\)",
                 r"\1ref(\2, supplement: none)", src)

    # @fig:x -> #ref(<fig:x>). See the module docstring: pandoc reads the @ as
    # citation syntax, so leaving these alone turns every cross-reference into
    # stray prose. Citations (@lovelace1843) are deliberately untouched. The
    # label part repeats typst_prose.CITE's segment class because labels may
    # be multi-segment (@fig:panel:a); capturing one segment truncated them.
    src = re.sub(rf"@({'|'.join(FLOAT_PREFIX)}):"
                 rf"([A-Za-z0-9_-]+(?::[A-Za-z0-9_-]+)*)",
                 r"#ref(<\1:\2>)", src)

    # Rejoin citation clusters the 80-column reflow split across lines. Typst
    # groups adjacent citations across a soft line break, so the PDF collapses
    # `@a @b @c\n@d @e @f` into one range (10-15); pandoc's Typst reader only
    # groups citations on ONE line, so the same source shipped a Word export
    # reading "10-12 13-15". Only a single newline is joined -- a blank line is
    # a paragraph break and never sits inside a citation cluster. Runs after
    # the @fig:/@tbl: rewrite above, so every surviving `@` is a citation.
    src = re.sub(rf"({typst_prose.CITE})\n[ \t]*(?={typst_prose.CITE})",
                 r"\1 ", src)
    return _restore_raw(src, raw_spans)


# A float's label, standing on its own after the #figure(...) call -- as
# opposed to inside a ref, where `<` directly follows `(`. Multi-segment, as
# everywhere else.
_DEF = re.compile(rf"(?<!\()<({'|'.join(FLOAT_PREFIX)}):"
                  rf"[A-Za-z0-9_-]+(?::[A-Za-z0-9_-]+)*>")
_HEADING = re.compile(r"(?m)^(=+)\s+\S[^\n]*$")
_REF = re.compile(r"(#?)ref\(\s*(<[^>]+>)\s*"
                  r"(,\s*supplement:\s*none\s*)?,?\s*\)")
_FIGURE_OPEN = re.compile(r"#?figure\(")
_CAPTION = re.compile(r"caption:\s*\[")


def resolve_crossrefs(head: str, body: str, native: list[dict] | None = None) -> str:
    """Every ref call becomes the literal text the PDF shows for it.

    Pandoc renders a Typst ref as an EMPTY link -- there is no page number to
    print and no target document to link into -- so every cross-reference
    silently vanished from the Word file: "see and here". What the PDF shows
    at that spot is text, and the numbering behind it is deterministic: floats
    count per kind in document order, headings nest, and the SI resets both
    with an "S" prefix (the #counter(...).update(0) block in paper.typ's back
    matter). This reimplements that count and writes the text in.

    The same count is written into the DEFINITIONS, not just the references:
    "Figure 3: " ahead of each caption, "2.1." (SI: "S2.1") ahead of each
    heading. Typst supplies those numbers at layout time and pandoc supplies
    nothing, so the Word file showed unnumbered captions under prose saying
    "Figure 3" -- every cross-reference pointed at a number no caption
    carried. Heading numbers follow the PDF's styles: arkheion's "1."
    pattern (trailing dot) for the main text, the back matter's "S1"
    function (no trailing dot) for the SI.

    `head` (title, authors, abstract) and `body` arrive separately because
    only the body is scanned for numbering -- the manuscript does not number
    the title or Abstract headings -- while references are REPLACED in both,
    since the abstract may point into the body. A ref to a label that no
    float or heading in the export defines is an error, not a link left to
    vanish: the target lives in the dropped back matter or nowhere, and
    either way the reader would get prose pointing at nothing.
    """
    head, head_spans = _protect_raw(head)
    body, body_spans = _protect_raw(body)

    numbered: dict[str, str] = {}
    actual = {f'<{r["label"]}>': r for r in native or [] if r["label"]}
    native_heads = iter(r for r in native or []
                        if r["kind"] == "heading" and r["number"] is not None)
    counters = {"fig": 0, "tbl": 0, "eq": 0}
    levels: list[int] = []
    si = False
    # (position, text) pairs written into `body` after the scan -- inserting
    # during it would shift every position the events were sorted on.
    inserts: list[tuple[int, str]] = []

    def number(n: int) -> str:
        return f"S{n}" if si else str(n)

    # Every #figure(...) call's span, so a def label can find the caption it
    # belongs to. Computed on the raw-protected body: a `#figure(` quoted in
    # backticks is prose, not a float.
    fig_spans = []
    for fm in _FIGURE_OPEN.finditer(mask(body, strings=True)):
        end = _paren_end(body, fm.end() - 1)
        if end is not None:
            fig_spans.append((fm.start(), end))

    if native is not None:
        figures = [r for r in native if r["kind"] == "figure"]
        if len(figures) != len(fig_spans):
            raise ResolveError("Word export cannot match all compiled figures to source; "
                               "use explicit figure() calls for exported figures")
        for (start, end), row in zip(fig_spans, figures):
            cap = _CAPTION.search(body, start, end)
            if cap and row["number"] is not None:
                inserts.append((cap.end(), f'{row["supplement"]} {row["number"]}: '))

    def caption_insert(label_at: int, prefix: str, num: str) -> None:
        """Queue "Figure 3: " onto the caption of the float labeled here.

        The label follows its #figure(...) call across whitespace only; a
        float without a caption (or an equation, which has none) is left
        alone -- the PDF shows no caption text to number there either.
        """
        span = next((s for s in fig_spans if s[1] <= label_at
                     and not body[s[1]:label_at].strip()), None)
        if span is None:
            return
        cap = _CAPTION.search(body, span[0], span[1])
        if cap:
            inserts.append((cap.end(), f"{SUPPLEMENT[prefix]} {num}: "))

    # Ref options outside this resolver's supported subset must fail visibly;
    # leaving them to pandoc can turn a reference into an empty link.
    for part in (head, body):
        for call in re.finditer(r"(?<![\w-])#?refn?\(", mask(part, strings=True)):
            if _REF.match(part, call.start()) is None:
                raise ResolveError("unsupported reference syntax; use ref(<label>) "
                                   "or refn(<label>) with optional supplement: none")
    definitions = mask(body, strings=True)
    definitions = _REF.sub(lambda m: "".join("\n" if c == "\n" else " "
                                            for c in m.group()), definitions)
    events = (
        [(m.start(), "def", m) for m in _DEF.finditer(definitions)]
        + [(m.start(), "head", m) for m in _HEADING.finditer(body)])
    if _SI_MARK in body:
        events.append((body.index(_SI_MARK), "si", None))
    for _, what, m in sorted(events, key=lambda e: e[0]):
        if what == "si":
            counters = {"fig": 0, "tbl": 0, "eq": 0}
            levels, si = [], True
        elif what == "head":
            depth = len(m.group(1))
            levels = levels[:depth] + [0] * (depth - len(levels))
            levels[depth - 1] += 1
            joined = ".".join(str(n) for n in levels)
            if native is None:
                inserts.append((m.end(1), f" S{joined}" if si else f" {joined}."))
            else:
                row = next(native_heads, None)
                if row is None:
                    raise ResolveError("Word export cannot match heading numbering to Typst")
                inserts.append((m.end(1), " " + row["number"]))
        else:
            prefix = m.group(1)
            if native is not None:
                row = actual.get(m.group(0))
                if row is None or row["number"] is None:
                    continue
                numbered[m.group(0)] = row["number"].rstrip(".")
                continue
            # A sec label names the heading it follows -- usually on the same
            # line, on its own line when typstyle wraps a long title. Either
            # way its def event sorts after the heading's bump, so "the
            # current number" is its number.
            if prefix == "sec":
                if levels:
                    numbered[m.group(0)] = \
                        ("S" if si else "") + ".".join(str(n) for n in levels)
                continue
            counters[COUNTER[prefix]] += 1
            numbered[m.group(0)] = number(counters[COUNTER[prefix]])
            if prefix != "eq":
                caption_insert(m.start(), prefix,
                               numbered[m.group(0)])

    for at, text in sorted(inserts, reverse=True):
        body = body[:at] + text + body[at:]

    if native is not None and next(native_heads, None) is not None:
        raise ResolveError("Word export did not preserve every numbered heading")

    def ref(m: re.Match) -> str:
        hash, label, bare = m.group(1), m.group(2), bool(m.group(3))
        if label not in numbered:
            raise ResolveError(
                f"reference to {label}, but no float or heading in the "
                f"export carries that label -- it lives in the dropped back "
                f"matter, or nowhere. The reader would get prose pointing at "
                f"nothing.")
        prefix = label[1:].split(":", 1)[0]
        supplement = actual[label]["supplement"] if native is not None else SUPPLEMENT[prefix]
        text = numbered[label] if bare else f"{supplement} {numbered[label]}"
        # Markup-mode `#ref(...)` becomes plain prose; a code-mode call sits
        # in an argument list, where bare words are an error and a content
        # block `[...]` is the literal it meant.
        return text if hash else f"[{text}]"

    head = _restore_raw(_REF.sub(ref, head), head_spans)
    body = _restore_raw(_REF.sub(ref, body), body_spans)
    return (head + body).replace(_SI_MARK, "")


def export_includes(src: str, path: Path, stack=()) -> str:
    """Inline captured includes for Word, preserving nested relative paths."""
    if path in stack:
        raise ResolveError(f"cyclic include: {path}")
    stack = (*stack, path)
    visible = mask(src, strings=True)
    edits = []
    for m in re.finditer(r'(#?)include\s+"([^"]+)"', src):
        if not visible[m.start():m.start() + 1].strip():
            continue
        target = (ROOT / m[2].lstrip("/") if m[2].startswith("/")
                  else path.parent / m[2]).resolve()
        if not target.is_relative_to(ROOT.resolve()):
            raise ResolveError(f"include outside captured manuscript: {m[2]}")
        content = export_includes(target.read_text(), target, stack)
        content = resolve_notation(content, {}, str(target.relative_to(ROOT)))
        mark = _SI_MARK + "\n" if target == ROOT / "si-body.typ" else ""
        edits.append((m.start(), m.end(), m[1] + "[\n" + mark + content + "\n]"))
    # Resolve image paths against the file they were written in, before the
    # include loses that scope. Pandoc receives project-relative paths.
    for m in re.finditer(r'(?<![\w.-])image\(\s*"([^"]+)"', src):
        if not visible[m.start():m.start() + 1].strip():
            continue
        target = (ROOT / m[1].lstrip("/") if m[1].startswith("/")
                  else path.parent / m[1]).resolve()
        if not target.is_relative_to(ROOT.resolve()):
            raise ResolveError(f"image outside captured manuscript: {m[1]}")
        edits.append((m.start(1), m.end(1), target.relative_to(ROOT).as_posix()))
    for start, end, value in sorted(edits, reverse=True):
        src = src[:start] + value + src[end:]
    return src


def _paren_end(src: str, at: int) -> int | None:
    """Index just past the `)` matching the `(` at `at`, or None."""
    depth = 0
    for i in range(at, len(src)):
        if src[i] == "(":
            depth += 1
        elif src[i] == ")":
            depth -= 1
            if depth == 0:
                return i + 1
    return None


def _call_span(src: str, opener: str) -> str | None:
    """The full text of `opener ... )` with balanced parentheses, or None."""
    at = src.find(opener)
    if at < 0:
        return None
    end = _paren_end(src, at + len(opener) - 1)
    return None if end is None else src[at:end]


def bibliography_line(paper_src: str, config_src: str) -> str:
    """The manuscript's #bibliography(...) call, made self-contained.

    It sits in paper.typ's back matter -- outside the BODY markers -- so the
    body slice drops it, and without it every citation in the export dangles:
    Typst cannot resolve the @keys and citeproc has no entries to set. The
    call is carried through verbatim except for one substitution: `style:`
    usually names a config.typ variable (`paper-bib-style`), whose `#let` does
    not travel, so the identifier is resolved to its string literal here.

    Returns "" for a manuscript with no bibliography, which is legal.
    """
    call = _call_span(_strip_comments(paper_src), "#bibliography(")
    if call is None:
        return ""
    return _bib_style(call, config_src, "#bibliography")


def _bib_style(call: str, config_src: str, where: str) -> str:
    """`style: paper-bib-style` -> `style: "american-chemical-society"`.

    A bibliography call usually names a config.typ variable for its style, and
    the `#let` behind it does not travel into the projection. Pandoc is handed
    the CSL by name downstream, so the name has to be a literal by then.
    """
    m = re.search(r"style:\s*([A-Za-z_][A-Za-z0-9_-]*)\b", call)
    if not m or m.group(1) == "none":
        return call
    let = re.search(rf'#let\s+{re.escape(m.group(1))}\s*=\s*"([^"]+)"',
                    _strip_comments(config_src))
    if not let:
        raise ResolveError(
            f"{where}(style: {m.group(1)}): no "
            f'`#let {m.group(1)} = "..."` in config.typ to resolve it '
            f"from. Name a string literal, or define the variable there.")
    return call.replace(m.group(0), f'style: "{let.group(1)}"')


def resolve_si_bibliography(si_src: str, paper_src: str, config_src: str) -> str:
    """The SI's Alexandria reference list, rewritten as plain Typst.

    The SI carries its own reference list because it is submitted as its own
    file. Typst allows one native #bibliography per document, so the PDF sets
    the SI's with Alexandria: `#show: alexandria(prefix: "si-")` in paper.typ,
    `#bibliographyx(..., prefix: "si-")` in si-body.typ, and every SI citation
    written `@si-key`.

    None of that means anything to pandoc, and the prefix is not part of any
    citation key: `si-hopper1952` is in no .bib file, and citeproc would set
    it as bold prose. So here the call becomes an ordinary #bibliography and
    the SI's citations lose the prefix, leaving two plain bibliography calls
    in the projection for export_docx.py to convert one at a time.

    The projection consequently no longer compiles as a standalone Typst
    document -- Typst refuses the second call. It is read by pandoc, by the
    review diff, and by a person checking the prose, none of which compile it.

    A manuscript with no SI bibliography is returned unchanged.
    """
    si = si_bibliography(sources={"paper.typ": paper_src, "si-body.typ": si_src})
    if si is None or si["span"] is None:
        return si_src
    if si["prefix"] and si["list_prefix"] and si["prefix"] != si["list_prefix"]:
        raise ResolveError(
            f'paper.typ routes @{si["prefix"]}... to the SI bibliography but '
            f'si-body.typ prints one for @{si["list_prefix"]}...; the two '
            f"prefixes must match (`just prose-check` reports this too)")

    call = si["call"]
    plain = call.replace("#bibliographyx(", "#bibliography(", 1)
    plain = re.sub(r"\s*prefix:\s*\"[^\"\n]*\"\s*,?", "", plain, count=1)
    plain = _bib_style(plain, config_src, "#bibliographyx")

    # The label and the heading-numbering switch are layout, not content: the
    # label is wordcount.typ's exclusion handle and the `#set` keeps the SI's
    # S1/S2 numbering off the reference heading. Both would reach pandoc as
    # stray markup, so the rewrite takes the whole arrangement.
    return without_si_bibliography(si_src, paper_src, replacement=plain)


def _back_matter(paper_src: str, assets: dict) -> str:
    """The prose between BODY END and the bibliography, resolved.

    Associated Content, Author Information, Acknowledgment: it is back matter
    by the word-count's definition, but it is CONTENT -- a journal reads the
    data-availability statement and the author list from the Word file -- and
    dropping it with the template shipped exports missing all three sections.
    The slice ends at the #bibliography call; failing that, at the first
    piece of SI-appendix machinery (page break, si-body include), which is
    layout and counter surgery no converter can use.
    """
    m = readability.BODY_END.search(paper_src)
    if not m:
        return ""
    tail = paper_src[m.end():]
    cut = len(tail)
    for anchor in ("#bibliography(", "#pagebreak()",
                   '#include "si-body.typ"'):
        at = tail.find(anchor)
        if 0 <= at < cut:
            cut = at
    return resolve_notation(tail[:cut], assets,
                            "paper.typ (back matter)").strip()


def _names(meta: dict) -> str:
    """The plain author names, comma-joined -- si-authors, rebuilt.

    Tolerates both the probe's (name, affils) records and bare strings, so
    a test can hand in names without inventing affiliations.
    """
    return ", ".join(a["name"] if isinstance(a, dict) else a
                     for a in meta.get("authors", []))


def _author_line(meta: dict) -> str:
    """The author line with affiliation superscripts, as the PDF prints it.

    "Patrick Garrett#super[1], Jolene K. Diedrich#super[1,2]": the numbers
    are Typst's own (the probe maps each affiliation to its position in
    paper-affiliations), and pandoc reads #super natively. Without them the
    export showed a bare name list above a numbered affiliation list that
    nothing pointed into. An author with no resolvable affiliation gets no
    marker rather than an empty superscript.
    """
    parts = []
    for a in meta.get("authors", []):
        if isinstance(a, str):
            parts.append(a)
            continue
        nums = ",".join(str(n) for n in a.get("affils", []))
        parts.append(a.get("name", "") + (f"#super[{nums}]" if nums else ""))
    return ", ".join(parts)


def _si_title(meta: dict) -> str:
    """The SI's title block: what the PDF centers ahead of the appendix.

    paper.typ builds it from align/text primitives, which do not travel, so
    it is synthesized here from the same front matter.
    A #heading CALL rather than `= ` markup, for the same reason the PDF
    passes `numbering: none`: the crossref pass numbers markup headings, and
    this one must not tick Section S1 away from the SI's first real section.
    Plain names, no affiliation markers -- exactly what si-authors shows.
    """
    authors = _names(meta)
    return ("#heading(level: 1, numbering: none, outlined: false)"
            "[Supporting Information]\n\n"
            f"{meta.get('title', '')}\n\n"
            + (f"_{authors}_\n\n" if authors else ""))


def _toc_block(paper_src: str, assets: dict) -> str:
    """The abstract/TOC graphic and its caption, when the front matter has one.

    The convention is paper.typ's own: `#let toc-graphic = ...` (usually a
    fig() call) with an optional `#let toc-caption = [...]` beside it. Both
    sit in layout wrappers the export cannot use, so the bindings are read
    directly and emitted as plain content -- image, then italic caption --
    image, then italic caption. A manuscript
    without the binding gets "" and no TOC graphic, which is legal.
    """
    m = readability.BODY_START.search(paper_src)
    front = _strip_comments(paper_src[:m.start()] if m else paper_src)
    g = re.search(r"(?m)^#let\s+toc-graphic\s*=\s*(\S.*)$", front)
    if not g:
        return ""
    expr = g.group(1).strip()
    block = resolve_notation(expr if expr.startswith("#") else "#" + expr,
                             assets, "paper.typ (toc-graphic)").strip()
    c = re.search(r"#let\s+toc-caption\s*=\s*\[", front)
    if c:
        # The same bracket walk as the abstract: a regex to `]` truncates the
        # caption at the first nested bracket.
        depth = 0
        for i in range(c.end() - 1, len(front)):
            if front[i] == "[":
                depth += 1
            elif front[i] == "]":
                depth -= 1
                if depth == 0:
                    cap = resolve_notation(front[c.end():i].strip(), assets,
                                           "paper.typ (toc-caption)")
                    block += f"\n\n_{cap}_"
                    break
    if NATIVE_NUMBERING is not None:
        block = export_includes(block, ROOT / "paper.typ")
    return block


def build(front_matter: dict | None = None) -> str:
    if not ASSETS.is_file():
        assets = {}
    else:
        assets = json.loads(ASSETS.read_text()).get("values", {})

    meta = _query_front_matter() if front_matter is None else front_matter
    paper_src = (ROOT / "paper.typ").read_text()
    body = readability.slice_body(paper_src)
    if NATIVE_NUMBERING is not None:
        body = export_includes(body, ROOT / "paper.typ")
    body = resolve_notation(body, assets, "paper.typ")

    # Back matter and the bibliography, IN THE PDF'S ORDER: main text, then
    # Associated Content / Author Information / Acknowledgment, then the
    # references, then the SI. The bibliography used to be appended after
    # everything, which citeproc read literally -- the reference list landed
    # at the very bottom of the Word file, underneath the entire SI.
    back = _back_matter(paper_src, assets)
    if back:
        body += "\n\n" + back
    config_src = (ROOT / "config.typ").read_text()
    bib = bibliography_line(paper_src, config_src)
    if bib:
        body += "\n\n" + bib

    # The SI is read as its own file, exactly as readability.py and the
    # narrator read it. paper.typ DOES `#include "si-body.typ"`, but that line
    # sits outside the BODY markers -- back matter does, by this scaffold's
    # convention -- so slicing the body drops it. Following the include from
    # inside the body instead silently produced a manuscript with no SI and
    # therefore no tables, which is how this was found.
    #
    # UNLESS the include survived the slice: on a migrated manuscript the
    # markers are new and nothing enforces which side of them the include
    # landed on. Appending anyway would put the entire SI in twice -- once
    # here, once through the inliner below -- silently.
    si = ROOT / "si-body.typ"
    if si.is_file() and _SI_MARK not in body and not re.search(r'#include\s+"/?si-body\.typ"', body):
        # The marker sits on its own line so the SI's first heading still
        # starts a line, which is what the heading scan anchors on.
        si_src = export_includes(si.read_text(), si) if NATIVE_NUMBERING is not None else si.read_text()
        si_src = resolve_si_bibliography(si_src, paper_src, config_src)
        body += ("\n\n" + _SI_MARK + "\n" + _si_title(meta)
                 + resolve_notation(si_src, assets, "si-body.typ"))

    # Any OTHER include inside the body is inlined where it stands. The SI,
    # when its include survived inside the markers, is marked here instead:
    # the crossref pass needs to know where the counters reset.
    def inline(m: re.Match) -> str:
        # Typst resolves a leading "/" against the project root, not the OS's.
        target = ROOT / m.group(1).lstrip("/")
        if not target.is_file():
            raise ResolveError(f"paper.typ includes {m.group(1)}, which is missing")
        src = target.read_text()
        mark = ""
        if target == si:
            mark = _SI_MARK + "\n" + _si_title(meta)
            src = resolve_si_bibliography(src, paper_src, config_src)
        return mark + resolve_notation(src, assets, m.group(1))

    body = re.sub(r'#include\s+"([^"]+)"', inline, body)

    authors = _author_line(meta)
    affils = "\n".join(f"{i + 1}. {a}" for i, a in
                       enumerate(meta.get("affils", [])))
    abstract = resolve_notation(_abstract(), assets, "config.typ (abstract)")
    if NATIVE_NUMBERING is not None:
        abstract = export_includes(abstract, ROOT / "config.typ")
    keywords = ", ".join(meta.get("keywords") or [])
    toc = _toc_block(paper_src, assets)

    head = (
        f"{ABOUT}\n"
        f"= {meta.get('title', '')}\n\n"
        f"{authors}\n\n"
        f"{affils}\n\n"
        f"== Abstract\n\n{abstract}\n\n"
        + (f"*Keywords:* {keywords}\n\n" if keywords else "")
        + (toc + "\n\n" if toc else "")
    )
    return resolve_crossrefs(head, body, NATIVE_NUMBERING) + "\n"


def main(front_matter: dict | None = None) -> int:
    try:
        write_text(OUT, build(front_matter))
    except ResolveError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    n = len(OUT.read_text().splitlines())
    print(f"wrote {OUT.name} ({n:,} lines) -- plain Typst, for pandoc")
    return 0


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Adapt a captured manuscript for Word")
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--output", type=Path, default=OUT)
    parser.add_argument("--numbers", type=Path)
    parser.add_argument("--front-matter", type=Path)
    args = parser.parse_args()
    if args.numbers is None:
        # Direct invocations use the shared build too. Only the internal Word
        # adapter is allowed to consume a pre-captured tree and numbering map.
        from build_state import build as build_manuscript
        raise SystemExit(build_manuscript("resolve", args.root.resolve()))
    ROOT, OUT = args.root.resolve(), args.output.resolve()
    ASSETS = ROOT / "assets.json"
    typst_prose.STATS_JSON = ROOT / "stats.json"
    NATIVE_NUMBERING = json.loads(args.numbers.read_text()) if args.numbers else None
    front_matter = json.loads(args.front_matter.read_text()) if args.front_matter else None
    raise SystemExit(main(front_matter))
